### ISSUE TITLE
Model and module request

### ISSUE THREAD

**Issue by Vkzem** [fofr/cog-comfyui#10]
Hi Fofr big fan of your work :)

Could I kindly request:
1. [GroundingDino/SAM modules+models that underpin this linked repo](https://github.com/storyicon/comfyui_segment_anything)
2. [ComfyUI_ImageProcessing nodes](https://github.com/bvhari/ComfyUI_ImageProcessing)
3. [WAS node suite](https://github.com/WASasquatch/was-node-suite-comfyui)

If helpful, for 1. above's models, it looks like model [GroundingDINO_SwinB](https://huggingface.co/ShilongLiu/GroundingDINO/resolve/main/groundingdino_swinb_cogcoor.pth) is saved in `models/grounding-dino` and [sam_vit_h](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth) is saved in `models/sams`.

One other question - is there a way we can upload our own custom LORA to this setup at predict-time? 

Thank you very much!

**Comment by fofr** [comment]
I'm working on adding WAS node suite now, I'll take a look at the other modules once that one is working. It's big and complex, but has been requested a lot now.

**Comment by fofr** [comment]
No way to upload custom LoRA at the moment

**Comment by Vkzem** [comment]
Thanks a lot - appreciate your hard work 🙏

**Comment by fofr** [comment]
This PR adds support for the SAM weights:
https://github.com/fofr/cog-comfyui/pull/22

Still working on WAS nodes.

**Comment by fofr** [comment]
PR to add WAS nodes:
https://github.com/fofr/cog-comfyui/pull/25

**Comment by fofr** [comment]
PR to add comfyui_segment_anything:
https://github.com/fofr/cog-comfyui/pull/26

**Comment by fofr** [comment]
Hi @Vkzem – I'm probably not going to add `ComfyUI_ImageProcessing` as it isn't a super popular custom node.

Otherwise I think everything you requested is now added.
