### ISSUE TITLE
Request add Image Resizing and Image Gaussian Blur

### ISSUE THREAD

**Issue by zaheenrahman** [fofr/cog-comfyui#101]
Hi,

I'm wondering if these 2 nodes can be added. 

![image](https://github.com/fofr/cog-comfyui/assets/35182751/ff036ed9-788a-408e-9271-5fe7a81ea6b3)

![image](https://github.com/fofr/cog-comfyui/assets/35182751/12010f4b-62be-4495-b78a-ba6db23764cb)

Or if alternatives can be suggested. I really like having the image to have a larger side of 896 so I can do an outpainting pad of 128 pixels to have a nice 1024px image for outpainting. 

Thank you so much in advance.

**Comment by fofr** [comment]
Try ImageResize+ from https://github.com/cubiq/ComfyUI_essentials

<img width="223" alt="Screenshot 2024-06-11 at 10 52 45" src="https://github.com/fofr/cog-comfyui/assets/319055/ed06171f-b6b7-4c5f-a34f-06cb352e9445">

ImageGuassianBlur comes from https://github.com/sipherxyz/comfyui-art-venture and is not supported.

Do these modules work?
<img width="290" alt="Screenshot 2024-06-11 at 11 01 53" src="https://github.com/fofr/cog-comfyui/assets/319055/dee6740f-b8b1-4a3f-8dc7-9594378663df">

**Comment by zaheenrahman** [comment]
Hi Fofr, thanks for the response. I'll try them out immediately and see if they work for me. Thanks!

**Comment by fofr** [comment]
Closing this for now, but feel free to reopen if you still have issues.
