### ISSUE TITLE
Pony Diffusion

### ISSUE THREAD

**Issue by Skallagrimr** [fofr/cog-comfyui#105]
Any plans to add Pony Diffusion models?

**Comment by fofr** [comment]
You can also try to add your own now via:
https://replicate.com/fofr/any-comfyui-workflow/train

**Comment by Skallagrimr** [comment]
Many folks are using basic one v6, would be very helpful https://huggingface.co/LyliaEngine/Pony_Diffusion_V6_XL

**Comment by fofr** [comment]
I've added support for this now.
