### ISSUE TITLE
StyleAligned Workflow

### ISSUE THREAD

**Issue by JaviSt97** [fofr/cog-comfyui#106]
Hi there,
I've skimmed through the available nodes and I don't think the necessary ones are there. Essentially:

- Style Aligned for ComfyUI [https://github.com/jasonphillips/styl...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbjdIMGhzWnpNVDBHTW1hUDlGYW9Sb295NWNld3xBQ3Jtc0tsNHZ2dXM5S2VEOXJseS1HVG91SGdQZFc4NzhyUU4yLWFpRktjU0lpdHlFNFF3azA2N3VTWlhmOW1XQzkwWmJFWE5NYzFCQlF5NTBGM0F2YVZGNWlaMmhPM2N5VmZKX3hlLWVFWXFmU2dFNXA0SVNrRQ&q=https%3A%2F%2Fgithub.com%2Fjasonphillips%2Fstyle_aligned_comfy&v=LIuKTn6ScZk)
- Prompt Batch Scheduler - [https://github.com/FizzleDorf/ComfyUI...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbFI2bkdGcXdZRWdaTmNfX2xiVjlmU1hyXzhvZ3xBQ3Jtc0trSDhYMVRtSjZfLWNiWWxWU0NWdzBqZ2NKOEtKVzE2bldxc29JVkt0MmlaUUJ4UnR1OFc0YW8zSmNlQkdLUlJLSWZXSDBaRUlxTVdkUG9aNFVyZkYtMFZoQUxXYW53TWItMVN1ajl4clhHUjVLdkpBaw&q=https%3A%2F%2Fgithub.com%2FFizzleDorf%2FComfyUI_FizzNodes&v=LIuKTn6ScZk)
- Global Seed - [https://github.com/ltdrdata/ComfyUI-I...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqblNYUjR4cDR6aDBvT3hUdF9mdUt0bkxBOXJsd3xBQ3Jtc0ttOVdCeUJUWmNjcG9TTmNVWFB5YkVoWTFjX25jNXZZNFhXai1TLV8xeXBmRkdoakNKR1dnbmR3UUt4bEphQnpCQzVvNjJkT0Mxc0h6MjlFZU53QklNMWVMVU51Q01sR05mSnEwb1FkYlZjRlBpc1E4Zw&q=https%3A%2F%2Fgithub.com%2Fltdrdata%2FComfyUI-Inspire-Pack&v=LIuKTn6ScZk)

Each of them are required to make this work (Example [workflow](https://www.youtube.com/watch?v=LIuKTn6ScZk)). Replicate does have a style aligned API from [lucataco](https://replicate.com/lucataco/style-aligned), but it's somewhat limited in that we can't really pick the checkpoint nor add any pre-conditioning such as IP Adapters.

Thank you !

**Comment by fofr** [comment]
Does Style Align offer anything better than Style Transfer from IPAdapters?

FizzNodes and ImpactPack custom nodes are already available.

**Comment by JaviSt97** [comment]
Thanks for the reply !
Great good to know – as for Style Align I've found it to be incredibly more consistent in terms of actual style transfer , without any bleeding from the composition. I use it for pretty much anything consistency-related now.

On that note, Latent Vision [published](https://www.youtube.com/watch?v=ewKM7uCRPUg&t=142s&ab_channel=LatentVision) few days ago a new weight type for IPAdapter that supposedly singles out efficiently the unet block responsible for style transfer to avoid bleeding. Haven't tried it yet, I'll update this here to see if it's on par with style align performance asap.

**Comment by JaviSt97** [comment]
For reference –
This is the image used for style transfer:
<img src="https://github.com/fofr/cog-comfyui/assets/162743219/209e6d73-2f4c-4d63-a146-6ebca03682d7" width="200" />

I used the prompt _illustration of a basket of cherry tomatoes, cut-out on white background_ for both.
Here is the result using IP Adapter with precise style transfer
<img src="https://github.com/fofr/cog-comfyui/assets/162743219/39451b7f-ada0-499f-84e5-f803fa08227f" width="200" />
Here using Style Aligned :
<img src="https://github.com/fofr/cog-comfyui/assets/162743219/47aea818-40a2-4371-91e2-444a645f26c1" width="200" />

While Style Align bleeds a bit of the reference image messiness, I find the resulting style much more aligned (whimsical, lighthearted ..) – The composition itself could then be improved with prompt weights and / or controlnets on top.

**Comment by JaviSt97** [comment]
Any news ?
