### ISSUE TITLE
Request for some additional custom node

### ISSUE THREAD

**Issue by prehnRA** [fofr/cog-comfyui#11]
Hello! Thanks for putting this together.

We're currently using a custom forked version of this image to implement this workflow: https://openart.ai/workflows/publicprompts/stylized-text/st72sLEJUMZtznCAKsiM. We were wondering if it would be possible / desired to add a few sets of custom nodes to this model so that we could use the base model directly and other folks in the community could easily use the same workflow.

The custom node sets currently not included that are required for the stylized-text workflow:
- https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes
- https://github.com/WASasquatch/was-node-suite-comfyui
- https://github.com/Stability-AI/stability-ComfyUI-nodes

If you are OK with including those, I'd be happy to prepare a PR to add them. Let me know what you think.

**Comment by fofr** [comment]
I'll add `[was-node-suite-comfyui](https://github.com/WASasquatch/was-node-suite-comfyui)` first, it's complex so might take a little while, but it's been frequently requested.

**Comment by fofr** [comment]
WAS nodes are now supported.
