### ISSUE TITLE
Can you get back an output that is not an image?

### ISSUE THREAD

**Issue by ParthGandhi** [fofr/cog-comfyui#110]
Lets say my workflow has an intermediary integer (eg image size) that I also want to include in the output. How would I do that?

Ideally i should be able to return an arbitrary JSON

From what I can tell, its not quite possible. But maybe I can write the data to a temporary file on disk and that gets returned instead?

**Comment by ParthGandhi** [comment]
Update: I tried installing `https://github.com/crystian/ComfyUI-Crystools` to use the `Any to JSON` node, but for whatever reason that lib doesn't get installed. I've been able to install other custom nodes without an issue. 

Any idea why? I added it to `custom_nodes.json` and re-built it.

**Comment by fofr** [comment]
You probably need to include the other dependencies from:
 https://github.com/crystian/ComfyUI-Crystools/blob/main/requirements.txt
 
 In cog.yaml

**Comment by ParthGandhi** [comment]
Would that not show up as an error? The logs are clean

**Comment by ParthGandhi** [comment]
Ok, that fixed it. Thank you!
