### ISSUE TITLE
TensorRT falls back to other execution providers - Image rembg (remove background) from WAS suite

### ISSUE THREAD

**Issue by aichromator** [fofr/cog-comfyui#111]
Hi, I am using **"Image rembg (remove background) from WAS suite"** node in comfy UI. It works fine and generates results in replicate (any-comfyui-workflow) but it takes a lot of time. The message I get in Keylog is mentioned below. Any help on how can I resolve this, please?

message - 

*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/python/onnxruntime_pybind_state.cc:456 void onnxruntime::python::RegisterTensorRTPluginsAsCustomOps(onnxruntime::python::PySessionOptions&, const ProviderOptions&) Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.

**Comment by fofr** [comment]
Do you have an example prediction to help me debug?

**Comment by aichromator** [comment]
Please see json below. You can use this to debug.

{
  "1": {
    "inputs": {
      "image": "input.png",
      "upload": "image"
    },
    "class_type": "LoadImage",
    "_meta": {
      "title": "Load Image"
    }
  },
  "2": {
    "inputs": {
      "width": 1024,
      "height": 1024,
      "interpolation": "nearest",
      "method": "stretch",
      "condition": "always",
      "multiple_of": 0,
      "image": [
        "1",
        0
      ]
    },
    "class_type": "ImageResize+",
    "_meta": {
      "title": "🔧 Image Resize"
    }
  },
  "3": {
    "inputs": {
      "transparency": true,
      "model": "u2net",
      "post_processing": false,
      "only_mask": false,
      "alpha_matting": false,
      "alpha_matting_foreground_threshold": 240,
      "alpha_matting_background_threshold": 10,
      "alpha_matting_erode_size": 10,
      "background_color": "none",
      "images": [
        "2",
        0
      ]
    },
    "class_type": "Image Rembg (Remove Background)",
    "_meta": {
      "title": "Image Rembg (Remove Background)"
    }
  },
  "4": {
    "inputs": {
      "images": [
        "3",
        0
      ]
    },
    "class_type": "PreviewImage",
    "_meta": {
      "title": "Preview Image"
    }
  }
}

**Comment by fofr** [comment]
Your output is a PreviewImage, make sure you either:

- return temporary images
- change that to a SaveImage node

https://replicate.com/p/f1429c5sgdrgp0cgv6g86s98tw
