### ISSUE TITLE
request for custom node addition (https://github.com/kijai/ComfyUI-IC-Light)

### ISSUE THREAD

**Issue by aichromator** [fofr/cog-comfyui#113]
Hi,

Please add the node for ComfyUI-IC-light (https://github.com/kijai/ComfyUI-IC-Light)

The custom node available (*ic-light-native*) also recommends the above node. Most of the community members I know are building using the node and its difficult to work without it.

"[ComfyUI-IC-Light](https://github.com/kijai/ComfyUI-IC-Light): The IC-Light impl from kijai. It includes a very useful DetailTransfer node to help preverse high frequency details from input fg image."

**Comment by dejangpt** [comment]
Yes! I need that as well to test my workflow.

**Comment by fofr** [comment]
I've added this in https://github.com/fofr/cog-comfyui/commit/03316cc266a5fe0058a95bc466bab03821edcb37
