### ISSUE TITLE
Request for adding LoRa from: https://civitai.com/models/7252/charturnerbeta-lora-experimental

### ISSUE THREAD

**Issue by zju7fdu** [fofr/cog-comfyui#114]
Hi,

Can you add the LoRa named CharTurnerBeta from https://civitai.com/models/7252/charturnerbeta-lora-experimental,

I have tried a lot of LoRas, I think this LoRa has the best ability in turning a correct angle for a specific character.

Thanks a lot!

**Comment by fofr** [comment]
Added in https://github.com/fofr/cog-comfyui/commit/c3d7132166120d4fb6371813471ab6883b6c402d
