### ISSUE TITLE
Please add ComfyUI-Gaffer

### ISSUE THREAD

**Issue by dejangpt** [fofr/cog-comfyui#116]
https://github.com/huagetai/ComfyUI-Gaffer

Also iclight_sd15_fc.safetensors https://huggingface.co/lllyasviel/ic-light/blob/main/iclight_sd15_fc.safetensors

**Comment by fofr** [comment]
I've added the original iclight weights:
https://github.com/fofr/cog-comfyui/commit/fe1b20db381a683852de3d0a32c83070d9c4de3d

**Comment by fofr** [comment]
Please use the more popular nodes for ICLight, either:

https://github.com/huchenlei/ComfyUI-IC-Light-Native
https://github.com/kijai/ComfyUI-IC-Light
