### ISSUE TITLE
Please add HD Helper

### ISSUE THREAD

**Issue by Jivanni** [fofr/cog-comfyui#117]
https://civitai.com/models/110071/hd-helper

**Comment by Jivanni** [comment]
Hi, Comfyui loads Lycoris as Loras, you can put it in the loras folder and load it with the Load Lora node as far as I know.

**Comment by fofr** [comment]
Cool, I've added this now
https://github.com/fofr/cog-comfyui/commit/21bff979c3750b4b98595a4e56521df14d8ad0a1
