### ISSUE TITLE
Updating Gourieff/comfyui-reactor-node Node

### ISSUE THREAD

**Issue by jamesblackwell** [fofr/cog-comfyui#118]
Are there any plans to update to the latest [Gourieff/comfyui-reactor-node? ](https://github.com/Gourieff/comfyui-reactor-node)?

There have been numerous recent updates and workflows do not work on the latest Cog version, namely because ReActorFaceBoost has been introduced and the MaskingHelper on the current Cog version isn't working as well.  

https://github.com/Gourieff/comfyui-reactor-node/commits/main/

**Comment by fofr** [comment]
Oh nice, these updates look great.

I've updated and will push a new model to Replicate soon.

https://github.com/fofr/cog-comfyui/commit/3d6c19d20b518fcc75e7944ca1cadd41b8a03fb9

**Comment by jamesblackwell** [comment]
Awesome, thanks @fofr !

**Comment by jamesblackwell** [comment]
I upgraded to the latest Cog, however my workflow doesn't work properly using the new Reactor Nodes:

<img width="1148" alt="Screenshot 2024-07-18 at 08 59 56" src="https://github.com/user-attachments/assets/68ea74af-55c4-47e4-b6a8-59d42773bdba">

It runs, but the face in the resulting image is blacked out. This doesn't happen when running the same workflow via Runpod. 

Any idea what might be the issue?

**Comment by fofr** [comment]
Oh that's really weird, do you have a workflow you can share? Feel free to email me (fofr @ repicate.com) if you need to keep it private.

**Comment by jamesblackwell** [comment]
Sure, I'll email it over now. Thanks

**Comment by fofr** [comment]
@jamesblackwell It seems to be an issue with `inswapper_128_fp16.onnx`, switching it to `inswapper_128.onnx` worked for me. No idea why though.

**Comment by jamesblackwell** [comment]
Thanks, this fix works
