### ISSUE TITLE
Request for adding animate diff LoRa from shatterAnimatediff_v10

### ISSUE THREAD

**Issue by realazthat** [fofr/cog-comfyui#119]
Here: https://huggingface.co/ArtGAN/Controlnet/blob/94b10ac2bab3f128115c26585059dcbe439ca592/shatterAnimatediff_v10.safetensors

Thanks.

**Comment by fofr** [comment]
Added here:
https://github.com/fofr/cog-comfyui/commit/ab387fd4929b82d255ba5f19d9cc11d638389155
