### ISSUE TITLE
Model Request

### ISSUE THREAD

**Issue by Leemer0** [fofr/cog-comfyui#12]
Hi can I request the following model + lora?

Copax TimeLessXL - SDXL1.0 v8
https://civitai.com/models/118111?modelVersionId=198246

MODILL_XL - Modern Colorful Illustration Style LoRa
https://civitai.com/models/192139/modillxl-modern-colorful-illustration-style-lora

thanks appreciate it!

**Comment by fofr** [comment]
I've added both of these models in https://github.com/fofr/cog-comfyui/commit/24ace7a3b70b46bf2c428f432f15d0b85d907572
