### ISSUE TITLE
Custom validation failed for node: image - Invalid image file

### ISSUE THREAD

**Issue by swapnil281095** [fofr/cog-comfyui#120]
Hello,

I am working on image generation task using Replicate's elixir code for API call. Since I cannot send locally stored image as a request to Replicate API. I have updated the comfyUI workflow json and replaced local image path with hosted image's path url and below is the error I am getting:

I am new with the comfyUI and may be I have used an incorrect node.

Checking inputs
Downloading https://replicate.delivery/pbxt/KFkSv1oX0v3e7GnOrmzULGqCA8222pC6FI2EKcfuCZWxvHN3/newton_0.jpg to /tmp/inputs/newton_0.jpg
✅ /tmp/inputs/newton_0.jpg
====================================
Checking weights
Including weights for IPAdapter preset: STANDARD (medium strength)
⏳ Downloading CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors to ComfyUI/models/clip_vision
✅ CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors downloaded to ComfyUI/models/clip_vision in 1.82s, size: 2411.24MB
⏳ Downloading ProteusV0.4.safetensors to ComfyUI/models/checkpoints
✅ ProteusV0.4.safetensors downloaded to ComfyUI/models/checkpoints in 4.87s, size: 6617.77MB
⏳ Downloading ip-adapter_sd15.safetensors to ComfyUI/models/ipadapter
✅ ip-adapter_sd15.safetensors downloaded to ComfyUI/models/ipadapter in 0.22s, size: 42.57MB
⏳ Downloading ip-adapter_sdxl_vit-h.safetensors to ComfyUI/models/ipadapter
✅ ip-adapter_sdxl_vit-h.safetensors downloaded to ComfyUI/models/ipadapter in 0.69s, size: 666.04MB
====================================
Randomising seed to 34061991
Running workflow
got prompt
Failed to validate prompt for output 9:
* LoadImage 16:
- Custom validation failed for node: image - Invalid image file: https://replicate.delivery/pbxt/KFkSv1oX0v3e7GnOrmzULGqCA8222pC6FI2EKcfuCZWxvHN3/newton_0.jpg
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
ComfyUI error: 400 Bad Request
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 221, in _predict
result = predict(**payload)
File "/src/predict.py", line 115, in predict
self.comfyUI.run_workflow(wf)
File "/src/comfyui.py", line 240, in run_workflow
prompt_id = self.queue_prompt(workflow)
File "/src/comfyui.py", line 178, in queue_prompt
raise Exception(
Exception: ComfyUI Error – Your workflow could not be run. This usually happens if you’re trying to use an unsupported node. Check the logs for 'KeyError: ' details, and go to https://github.com/fofr/cog-comfyui to see the list of supported custom nodes.

**Comment by fofr** [comment]
Please can you share a link to your prediction so I can debug

**Comment by swapnil281095** [comment]
I ran this into replicate playground https://replicate.com/fofr/any-comfyui-workflow?prediction=09kzy7ndqhrgp0cgm5gvresysg
![Uploading Screenshot from 2024-07-11 22-33-50.png…]()

**Comment by fofr** [comment]
Thank you, I've found the bug.

Partial fix here, but I'm going to do a more airtight one shortly:
https://github.com/fofr/cog-comfyui/commit/b1547d48724a5f127799981496839530d07b840b

**Comment by swapnil281095** [comment]
@fofr , Thank you for the efforts. I now understood the issue, earlier code didn't supported workflow with duplicate urls. When I tried executing with different urls, it worked and moving forward it can also support duplicate urls.
