### ISSUE TITLE
Request for adding custom node mikey_nodes, for FilePrefixNode

### ISSUE THREAD

**Issue by realazthat** [fofr/cog-comfyui#123]
Here: https://github.com/bash-j/mikey_nodes, name "mikey_nodes" in ComfyUI manager.

**Comment by UdaynStore** [comment]
how long does it take for custom nodes to be added? moreover, it says on replicate page that we can "use the Github repo as a template to roll your own". how to do that?

**Comment by fofr** [comment]
No plans to add these custom_nodes to the main repo yet, but I'll leave this issue open to see if others want/need the nodes too and I'll reconsider.

If you really need these, you can fork the repo and add the node to `custom_nodes.json`
