### ISSUE TITLE
use the Github repo as a template to roll your own

### ISSUE THREAD

**Issue by UdaynStore** [fofr/cog-comfyui#124]
it says on replicate page that we can "use the Github repo as a template to roll your own". how to do that?

moreover, how long does it take for custom nodes to be added?

**Comment by fofr** [comment]
You need a solid understanding of:

- Comfy
- Python
- cog/docker

To roll your own at the moment.

Or you could use Replicate to make a deployment, meaning the GPUs will only run your workflows, which might be more efficient (but you have to pay for setup time and idle time)

**Comment by fofr** [comment]
See also:
https://github.com/fofr/cog-comfyui/issues/128
