### ISSUE TITLE
Request for addition of Lama remover (object) (e.g. - https://github.com/sipherxyz/comfyui-art-venture)

### ISSUE THREAD

**Issue by aichromator** [fofr/cog-comfyui#127]
Hi Fofr, thanks for adding Ic-light. 

I have another request for the addition of lama remover.

Background removal can be achieved in multiple ways but I am not getting a better way to remove foreground objects than using lama remover. One that worked well for me was. - https://github.com/sipherxyz/comfyui-art-venture

Can you please add this / or the relevant custom node?

**Comment by fofr** [comment]
Lama looks like a great thing to add, how about these nodes?
https://github.com/Acly/comfyui-inpaint-nodes

**Comment by aichromator** [comment]
inpainting takes time. lama is very fast and straightforward. lama picks up a single object in the foreground on its own as well. In terms of running a complex comfy UI process (multiple nodes), a single node point helps. 

On a separate note, wanted to get your views on the background remover node. Do you suggest any other background remover node other than BRIA?  I have tried unet and others but the results are not as good as Bria's.  Would be grateful, if you could guide if to any other resource.

**Comment by aichromator** [comment]
i should have looked better at the link you shared. this looks great too - Inpaint Models (LaMA, MAT) in the link you shared. i will try on local tomorrow and let you know the result.

**Comment by fofr** [comment]
BRIA is my goto background remover too, there is also layerdiffuse which can make images with native transparency.

**Comment by fofr** [comment]
@aichromator btw, what custom node shows you the custom node labels against the nodes?

**Comment by fofr** [comment]
I'll look at adding these tomorrow.

**Comment by aichromator** [comment]
Activate the names here - 

<img width="1022" alt="Screenshot 2024-07-23 at 7 37 15 AM" src="https://github.com/user-attachments/assets/c8de9dc7-2403-472f-80a2-48789c3819c1">

**Comment by aichromator** [comment]
Another good remove background option that I found yesterday was - https://github.com/plemeri/InSPyReNet.  It has a comfy node too.  The obvious reason for suggesting it is the MIT license.  The results are great (comparable to best and much better than unet, isnet etc)

It would be great if you could add a node for Inspyrenet.  

I am learning how to create a fork and do it on my own but I believe these nodes (suggested) will be useful to a wider audience as well :)

**Comment by fofr** [comment]
I've added in https://github.com/fofr/cog-comfyui/commit/77f7a93df868980cee7f9922ac2a1af3ae941270

Please can you try on:
https://replicate.com/fofr/any-comfyui-workflow

**Comment by aichromator** [comment]
This works well! 

Thank you again for :)
