### ISSUE TITLE
syntax for inline image upload?

### ISSUE THREAD

**Issue by tomryanx** [fofr/cog-comfyui#129]
Trying to pass an image to my workflows but I'm not clear on what format it should be in. For other models I've passed a base64-encoded string and it's worked great.

```
    version: "fda0aae05a1bd8c152e8501b4dcd74c2ad3e40cbf7c3ab5eef2b3c17ad80974f",
    input: {
      workflow_json,
      randomise_seeds: false,
      return_temp_files: false,
      image: image?.imageData,
    },
```

But this doesn't get the file. I'm guessing base64 is not what it needs. What does it need?

**Comment by fofr** [comment]
Have you tried this?

```
input: {
      workflow_json,
      randomise_seeds: false,
      return_temp_files: false,
      input_file: image?.imageData,
    },
```

**Comment by tomryanx** [comment]
No I haven't! Didn't see that documented anywhere :)

I've since just resorted to use s3... no biggy. Thanks anyway

**Comment by mirkancal** [comment]
Is it also how you upload zip file?
