### ISSUE TITLE
Add ComfyUI-Impact-Pack

### ISSUE THREAD

**Issue by digitaljohn** [fofr/cog-comfyui#13]
Hi, is there any chance we could get [ComfyUI-Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack) added to allow for Face Detailing?

**Comment by digitaljohn** [comment]
p.s. I am running this without issues on my fork, any reason why you may be hesitant?

**Comment by fofr** [comment]
Not hesitant, just busy. It's on my list, but I need to finish getting the WAS nodes working first.

**Comment by digitaljohn** [comment]
@fofr understood. I opened a PR to give you a starting point. Happy to help maintain. 👍🏼
