### ISSUE TITLE
Request support for checkpoint and LoRA

### ISSUE THREAD

**Issue by ygurzeev** [fofr/cog-comfyui#130]
LoRA - https://huggingface.co/Lykon/LoRA/blob/4ffdf07e28570fa7084fc4d34665ddff753be738/arcane_offset.safetensors
Checkpoint - https://civitai.com/models/530602?modelVersionId=609481

Thanks!

**Comment by fofr** [comment]
Added in:
https://github.com/fofr/cog-comfyui/commit/eb6cd9632cc1cf96babe06a6fbc8c740053c62ab
