### ISSUE TITLE
Request for addition of best in class background remover - https://github.com/ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO

### ISSUE THREAD

**Issue by aichromator** [fofr/cog-comfyui#140]
Hi Fofr,

Please add this custom node, works better than BRIA on extremely complex objects as well.

Link - https://github.com/ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO

**Comment by fofr** [comment]
WIP branch here while the above is pending:
https://github.com/fofr/cog-comfyui/compare/birefnet

**Comment by aichromator** [comment]
It's the same model and works with zho-zho-zho's node. Can you please merge it on the comfy-replicate. Only readme was updated yesterday.

<img width="1297" alt="Screenshot 2024-08-10 at 1 33 37 PM" src="https://github.com/user-attachments/assets/b5e1dc27-739d-4865-9f5e-17ecd1a4cb14">

**Comment by fofr** [comment]
This was merged and deployed
