### ISSUE TITLE
[Request] Flux.1 Schnell & Aura

### ISSUE THREAD

**Issue by bertagknowles** [fofr/cog-comfyui#142]
Request you to add the the following weights:

black-forest-labs/FLUX.1-schnell

**Comment by jordancoult** [comment]
We would also need the clip, text encoder, and VAE assets:
```
CLIP=https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/clip_l.safetensors
TEXT_ENC=https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp16.safetensors
VAE=https://huggingface.co/black-forest-labs/FLUX.1-schnell/resolve/main/ae.sft
MODEL=https://huggingface.co/black-forest-labs/FLUX.1-schnell/resolve/main/flux1-schnell.sft
```

In the `models/` directory, the above should be installed in `clip`, `clip`, `vae`, `unet`, respectively.

`.sft` and `.ae` should be renamed to `.safetensors` and `.vae`.

**Comment by fofr** [comment]
flux is now available

**Comment by mirkancal** [comment]
https://huggingface.co/XLabs-AI/flux-RealismLora/tree/main 🥺👉👈

**Comment by jordancoult** [comment]
@mirkancal Could you make a new issue for this request?

**Comment by fofr** [comment]
I'm on it :)
