### ISSUE TITLE
AnimateDiff now broken.

### ISSUE THREAD

**Issue by drommerkiller** [fofr/cog-comfyui#146]
It seems that something is updated and now animatediff workflows do not work anymore. I have local version and online version that has not been modified for a while and it suddenly stopped working.

Every workflow, even when used on Replicate form gives this error:
Executing node 41, title: Load AnimateDiff LoRA 🎭🅐🅓, class type: ADE_AnimateDiffLoRALoader
!!! Exception during processing!!! AnimateDiffLoraLoader.load_motion_lora() missing 1 required positional argument: 'name'
Traceback (most recent call last):
File "/src/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/src/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/src/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: AnimateDiffLoraLoader.load_motion_lora() missing 1 required positional argument: 'name'
Prompt executed in 1.54 seconds
outputs:  {}

Seems to relate to motion lora loader.

I have trained one own model and that still works, so this new bug has come after i trained that. Workaround for me is to use my own model for every workflow. Downside is that my own model has constant cold boots and can be really slow to use.

**Comment by fofr** [comment]
Can you share an example prediction or workflow? My guess is that the animate diff motion lora custom node has changed

**Comment by fofr** [comment]
Looks like you need to just pass in the name of the motion lora too?
https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/blob/c5c27807f0ba15507b8c9a7a650a04837351753a/animatediff/nodes_lora.py#L17

**Comment by fofr** [comment]
It used to be lora_name, now it's just name

<img width="655" alt="Screenshot 2024-08-21 at 11 06 23" src="https://github.com/user-attachments/assets/48003753-da8c-46d0-997f-d23509e0edf6">

**Comment by drommerkiller** [comment]
It was the name change problem. Now there is another problem for me:
* HighRes-Fix Script 241:
- Value not in list: control_net_name: '' not in []
- Value not in list: pixel_upscaler: '' not in []

HighRes-Fix Script used to work by leaving those empty as i'm only doing latent upscaling and those would just load extra files. Now it does not run trough if some value is empty. Is there workaround for that?

Thanks for checking this out!
Next time i'll try to remember to check the commit changes before posting here.

**Comment by drommerkiller** [comment]
> It used to be lora_name, now it's just name
> 
> <img alt="Screenshot 2024-08-21 at 11 06 23" width="655" src="https://private-user-images.githubusercontent.com/319055/359851940-48003753-da8c-46d0-997f-d23509e0edf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTMzNTgsIm5iZiI6MTcyNDc1MzA1OCwicGF0aCI6Ii8zMTkwNTUvMzU5ODUxOTQwLTQ4MDAzNzUzLWRhOGMtNDZkMC05OTdmLWQyMzUwOWUwZWRmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxMDA0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmY2ZTdkZmExNWJlZTAxOGJkMThkZmVlYmQ4NmJiYjA3MTg4N2EzZTE3ZjhmODYzM2EyZjcwYTFmMTUwZDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5WsaOglguCTU4KQJ0WIcUKtePj_r1eqLymSwOtKEv4U">


Changing lora_name to name gives this error: - Value not in list: name: '16000_cseti_4507345_general-70vid_mv2.safetensors' not in []
So it still checks is the name on some list before using it.
Are Motion loras copied to wrong directory?:
16000_cseti_4507345_general-70vid_mv2.safetensors exists in ComfyUI/models/animatediff_loras

That file should go to: ComfyUI\models\animatediff_motion_lora

**Comment by fofr** [comment]
I think this commit will fix it (I haven't pushed latest to Replicate yet)
https://github.com/fofr/cog-comfyui/commit/ca4ae0ec76a54874320797e4155d355872465c58

**Comment by fofr** [comment]
Fixed motion lora directory
