### ISSUE TITLE
Request: SAM2

### ISSUE THREAD

**Issue by jordancoult** [fofr/cog-comfyui#148]
Request for the Segment Anything 2 models in supported weights and a node that supports them. 
Namely, these custom nodes:
[https://github.com/kijai/ComfyUI-segment-anything-2](url)
[https://github.com/kijai/ComfyUI-Florence2](url)

Thanks!

**Comment by fofr** [comment]
I've added both of these
https://github.com/fofr/cog-comfyui/blob/main/CHANGELOG.md#2024-12-20
