### ISSUE TITLE
faceid LoRAs

### ISSUE THREAD

**Issue by digitaljohn** [fofr/cog-comfyui#15]
I do not think these are useable? They need to reside in the loras folder, not the ipadapters folder.

**Comment by fofr** [comment]
Do you have an example workflow? I can take a look.

**Comment by digitaljohn** [comment]
I believe this uses the `LoraLoaderModelOnly`...

https://openart.ai/workflows/bear_ill-fated_78/faceid-v2-comparison-workflow/5I6uRCPiET1TC3upb7gO

**Comment by fofr** [comment]
Thank you, I'm investigating

**Comment by fofr** [comment]
Thank you for reporting, I think this is now fixed in https://github.com/fofr/cog-comfyui/commit/949d4937362ad7061b202f1126a97af8e969199f
