### ISSUE TITLE
Shorten URL dont work in input file

### ISSUE THREAD

**Issue by lovisdotio** [fofr/cog-comfyui#155]
Prediction failed.

Unsupported file type:

As we are using pipedream, our link is not direct to the image, it can look something like that "https://tinyurl.com/3vtyts7v"
Sadly, if the link doesnt finish with .png or.zip, its automatcly detected as unsupported.
We test with other library on replicate and never had the issue.

Please let us know what is possible to do. We setup all our workflow with pipedream and we are stuck now.

**Comment by fofr** [comment]
Thanks for raising this, it deserves a proper fix. In the meantime, you could try hacking this in with:

```https://tinyurl.com/3vtyts7v?file_type=.jpg```

**Comment by fofr** [comment]
Fixed in b9dfee6
