### ISSUE TITLE
In need of custom nodes

### ISSUE THREAD

**Issue by glitzhigh** [fofr/cog-comfyui#157]
Dear dev team,
We are working on an AI Photobooth for an international airport. We'd love to make use of your services and run our workflow on replicate. We'd need the following custom nodes to be available : "comfyui_face_parsing", "JPS Custom Nodes for ComfyUI", "Allor Plugin", "comfy-plasma", "Comfy-Image-Selector", "Efficiency odes for ComfyUI V2.0+"

Or if there's a workaround I'd love to hear the steps I have to take. Thank you

Please let me know if that would be possible.

Kind regards,
Sara

**Comment by glitzhigh** [comment]
Or if there's a workaround I'd love to hear the steps I have to take. Thank you

**Comment by fofr** [comment]
@glitzhigh I typically only include popular custom nodes that many folks would use. As each custom node comes with a start up cost and adds complexity.

I would recommend forking/using this model as a template and adding these nodes to your own model.

You can add more nodes via `custom_nodes.js`, and by making sure all the necessary dependencies are in `cog.yaml`
