### ISSUE TITLE
LCM Motion Module

### ISSUE THREAD

**Issue by Inner-Reflections** [fofr/cog-comfyui#16]
Can you add the motion module noted here: https://huggingface.co/wangfuyun/AnimateLCM/tree/main I think the Lora is the usual LCM lora.

**Comment by Inner-Reflections** [comment]
The hotshot motion module would also be useful if is not too much trouble.

**Comment by Inner-Reflections** [comment]
How hard would it be to have the Depth Anything Preprocessor as well?

**Comment by fofr** [comment]
@Inner-Reflections Do you know which folder the motion module needs to go in?

**Comment by Inner-Reflections** [comment]
Same as any of the other motion modules (ie. temporaldiff, v3) etc.

**Comment by fofr** [comment]
I've added HotshotXL and AnimateLCM motion modules in https://github.com/fofr/cog-comfyui/commit/1b9d189d6e765593648565c6be03e02e76853802

Please can you let me know if you have any issues with them.

They are in the latest version of
https://replicate.com/fofr/any-comfyui-workflow

508be894cce01cff7e62eda09d6e1f58fe0cc09ecb7cb197698dcabc700af656
