### ISSUE TITLE
no output from replicate

### ISSUE THREAD

**Issue by mirkancal** [fofr/cog-comfyui#162]
My app stopped working this morning, after debugging, I realized there's no output coming from replicate.

No output on web when running sample config, I'm pretty sure it was returning some image:
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/83e0a91f-c8de-40ca-8405-1391f19c0dd1">

**Comment by mirkancal** [comment]
it was returning replicate.delivery urls, now only file name
<img width="769" alt="image" src="https://github.com/user-attachments/assets/1535e038-64d4-4991-96a4-215f4470cf0b">

**Comment by pocketens** [comment]
Also getting this issue. Reverting back to a version 3 months ago to try and get it to work.

**Comment by Ai-Artsca** [comment]
somethings def broke getting same empty output was working previously

**Comment by micos7** [comment]
Same

**Comment by levialevdeisgn** [comment]
same problem

**Comment by s-akamatsu-vb** [comment]
I have also the same problem.
Can anyone solve it?

**Comment by Ai-Artsca** [comment]
just tried another comfy ui replicate this one is working

https://replicate.com/135arvin/my_comfyui

**Comment by pablodecm** [comment]
We are also experiencing this, yet I do not see any clear cause in the latest changes to this PR cc @fofr.

**Comment by bertagknowles** [comment]
yes, same here. I thought I was the only one experiencing this. Pls resolve this urgently as users are unable to see the output files.

**Comment by pablodecm** [comment]
It seems that the latest version was deleted and it works again now.
![image](https://github.com/user-attachments/assets/99e2f1a2-ad62-4447-83f3-114e867f7ce9)

**Comment by bertagknowles** [comment]
Can these automatic version updates be stopped, so that we can use the old versions and not be automatically upgraded to new versions for the API.

**Comment by Lalimec** [comment]
what am i doing wrong, i still get no output from it.  https://replicate.com/135arvin/my_comfyui this also has no output. The weird thing is that i was able to work with my own fork of cog-comfy yesterday. Somehow they all got broken now.

https://replicate.com/p/j1zh42qvdnrgg0chxhjt11bzj0

**Comment by bertagknowles** [comment]
Again this problem is repeating. File has been generated but no output. 
![Untitled](https://github.com/user-attachments/assets/bbd32328-2ef2-4fb9-aee2-fcbda51ee8ff)
