### ISSUE TITLE
Request to add custom node ComfyUI-AdvancedLivePortrait

### ISSUE THREAD

**Issue by hellovoidworks** [fofr/cog-comfyui#163]
Seems popular with 1.1K stars and response on X. Would love to use it in a mobile or web app too -
https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait

**Comment by nitupaul91** [comment]
Any update?

**Comment by sourav-bhar** [comment]
Any updates on this please?

**Comment by fofr** [comment]
Added in b3e635681078e645a0bb8de96831edf986381c9d and c0a3afb79e922ba82c534d559e17ca57e8f76576
Sorry for the delay with this one.
