### ISSUE TITLE
optimize_image_files waste of 5s time

### ISSUE THREAD

**Issue by yzcaimz** [fofr/cog-comfyui#173]
After generating the image, optimize_image_files is re-saved at the default quality of 80%, which takes 5 seconds。
Generate image: 2048*2048, 2.4MB
optimized image: 2.1MB
The optimized pictures are reduced by 15% to 20%, but the inference service time is increased by 4 to 5 seconds, which is not worth it。

**Comment by fofr** [comment]
You can skip this by setting output to PNG and quality 100%
