### ISSUE TITLE
Request for at least 2 input image files and text prompt

### ISSUE THREAD

**Issue by bertagknowles** [fofr/cog-comfyui#18]
Can you add two input image files instead of only one and also the option to add text prompt for replicate api. Thanks.

**Comment by fofr** [comment]
You can zip up your inputs and pass in as many as you want. Or you can use URLs in the JSON instead of file paths.

**Comment by fofr** [comment]
Prompt is a good idea, I'll see if I can add that.

**Comment by bertagknowles** [comment]
Thanks for the quick response. A variable positive prompt as api input will be very helpful. I am working on an application and i send two image files (source file and reference file) in base64 format through replicate api. I am aware about zip and url inputs. Now my dilemma is that how will i send a zip file to replicate api just for another image. Also if i use a url to store my images in a firebase data store, the url will change with each image. Therefore two input images will be very helpful for this to work. Thanks for this awesome project.

**Comment by fofr** [comment]
The issue I'm seeing when looking into this is that both positive and negative prompts use CLIPTextEncode and look like this:

```"6": {
    "inputs": {
      "text": "some text",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
  "7": {
    "inputs": {
      "text": "some other text",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },```
  
  I wouldn't know which of these to update automatically with a given prompt field.

**Comment by bertagknowles** [comment]
Also can you please add SAM segmentation models. The base model will suffice. Thanks.

**Comment by fofr** [comment]
SAM models are being added here:
https://github.com/fofr/cog-comfyui/pull/22
