### ISSUE TITLE
Support Models to Better Interface with Krita Plugin

### ISSUE THREAD

**Issue by fawwazanvilen** [fofr/cog-comfyui#180]
[krita-ai-diffusion plugin](https://github.com/Acly/krita-ai-diffusion) is quite a popular plugin among digital artists that integrate ai to their workflow. it would be greatly appreciated if you could provide support for the [required models](https://github.com/Acly/krita-ai-diffusion) for this plugin to work with replicate's api.

the plugin relies on a ComfyUI backend, that we can provide locally or through the cloud.

**Comment by fofr** [comment]
All the custom nodes on https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup are currently supported

**Comment by fofr** [comment]
I've added all the necessary models in https://github.com/fofr/cog-comfyui/commit/a9b5f343cf7fa156bf72ed3b0b361dd646089ceb

I think this should be enough, but if you have problems feel free to re-open this issue.
