### ISSUE TITLE
Does the current <11gb file limit problem mean its currently impossible to train a FLux dev lora and use in my own workflow?

### ISSUE THREAD

**Issue by Dawgmastah** [fofr/cog-comfyui#186]
TItle 
Does the current <11gb file limit problem mean its currently impossible to train a FLux dev lora and use in my own workflow?

Is there another way to perhaps train a lora and use it from the  
https://replicate.com/fofr/any-comfyui-workflow/ model? I have been trying it to no success

**Comment by fofr** [comment]
Flux dev loras are small and this should work fine.
