### ISSUE TITLE
Controlnet model Request: CN-anytest_v3-50000_fp16.safetensors

### ISSUE THREAD

**Issue by maruhidd** [fofr/cog-comfyui#195]
**anytest_v3** is the most popular model in Japan. 

It can automatically recognize and apply various inputs, such as sketches, OpenPose, depth, and more. 

In anime-style illustrations, it has higher accuracy compared to other ControlNet models, making it a daily tool for almost all AI artists using Stable Diffusion in Japan. 

I sincerely hope it will be introduced.

[CN-anytest_v3-50000_fp16.safetensors](https://huggingface.co/2vXpSwA7/iroiro-lora/blob/main/test_controlnet2/CN-anytest_v3-50000_fp16.safetensors)

**Comment by maruhidd** [comment]
v3 is prior to v4

**Comment by fofr** [comment]
I've added these weights in 3d617ef, sorry for the delay
