### ISSUE TITLE
[Request] AAM_XL_AnimeMix Model

### ISSUE THREAD

**Issue by redstarxz** [fofr/cog-comfyui#198]
The current model list lacks models with animation styles. It is recommended to add the following model：

https://civitai.com/models/269232/aam-xl-anime-mix

https://huggingface.co/Lykon/AAM_XL_AnimeMix/tree/main

**Comment by fofr** [comment]
Added in https://github.com/fofr/cog-comfyui/commit/40101fc54f395268cf7a558ea99df8810ebbc647 👍
