### ISSUE TITLE
Issue with Controlnet advanced and Comfyui, need to update controlnet advanced on your side

### ISSUE THREAD

**Issue by lovisdotio** [fofr/cog-comfyui#201]
File \"/src/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control_plusplus.py\", line 227, in __init__\n super().__init__(control_model=control_model, global_average_pooling=global_average_pooling, device=device, load_device=load_device, manual_cast_dtype=manual_cast_dtype)\n" ], "current_inputs": { "name": [ "controlnet-union-promax-sdxl-1.0.safetensors" ], "plus_input": [ "<ComfyUI-Advanced-ControlNet.adv_control.control_plusplus.PlusPlusInputGroup object at 0x7fb82cb5bac0>" ] }, "current_outputs": [ "112", "111", "93", "5", "29", "89", "108", "7", "114", "54", "94", "8", "92", "13", "91", "33", "6", "124", "10", "28", "123", "3", "30", "85", "20", "4", "11", "50", "100", "31" ], "timestamp": 1731096602474 } }

Hello, 
It would need an update of controlnet advanced as you updated comfyui.
thanks

**Comment by fofr** [comment]
Thank you for highlighting this, I've fixed in 377de6430f31d89c8fe9d5361c3a1d823c07fff0 and pushed a new version to Replicate.
