### ISSUE TITLE
[Request] In-Context-LoRA

### ISSUE THREAD

**Issue by redstarxz** [fofr/cog-comfyui#202]
In-Context LoRA fine-tunes text-to-image models (e.g., [FLUX](https://huggingface.co/black-forest-labs/FLUX.1-dev)) to generate image sets with customizable intrinsic relationships, optionally conditioned on another set using SDEdit. It can be adapted to a wide range of tasks.

Project Page: https://ali-vilab.github.io/In-Context-LoRA-Page/

Loras:  https://huggingface.co/ali-vilab/In-Context-LoRA/tree/main

**Comment by fofr** [comment]
Is there a corresponding ComfyUI custom node for this?

**Comment by redstarxz** [comment]
> Is there a corresponding ComfyUI custom node for this?

No additional ComfyUI node support is needed, just use the normal Lora loader node.
Here is an example workflow for use with Flux model: 
https://github.com/ali-vilab/In-Context-LoRA/blob/main/workflow/film-storyboard.json

**Comment by fofr** [comment]
Added in https://github.com/fofr/cog-comfyui/commit/63902529341814bcc0baea8246bb6e95ebc03049
