### ISSUE TITLE
How can we use custom models with the replicate API?

### ISSUE THREAD

**Issue by FurkanGozukara** [fofr/cog-comfyui#204]
Lets say i want to use this particular FLUX LoRA how can we use it?

https://huggingface.co/MonsterMMORPG/3D-Cartoon-Style-FLUX/resolve/main/SECourses_3D_Render_Style_Fixed_Dataset_With_Captions.safetensors

this is a LoRA

what about fine tuning full checkpoints ?

Thank you so much @fofr we are building a huge application depending on replicate so we need to figure this out ASAP

**Comment by fofr** [comment]
I've added this in https://github.com/fofr/cog-comfyui/commit/cc906f7148138cb06a281c5d0fcd9b7d462be315
It should cycle through the GPUs on the live model over the next hour or so

**Comment by FurkanGozukara** [comment]
We are still waiting for this feature
