### ISSUE TITLE
models--CIDAS--clipseg-rd64-refined weight doesnt work

### ISSUE THREAD

**Issue by mehmetsat** [fofr/cog-comfyui#209]
I have tried to use this weight in my workflow as clipseg model but it doesnt work. So as a turned around I have put the model inside the docker which is not good, Could you check the model if it is properly supported in the files? Thank you

**Comment by fofr** [comment]
Do you have an example workflow to test with?

**Comment by mehmetsat** [comment]
ofcourse here is the example workflow 
[test_clipseg.json](https://github.com/user-attachments/files/17958365/test_clipseg.json)
here is the output logs at fofr/any-comfyui-workflow
`====================================
Inputs uploaded to /tmp/inputs:
input.png
====================================
Checking inputs
✅ /tmp/inputs/input.png
====================================
Checking weights
====================================
Running workflow
[ComfyUI] got prompt
Executing node 165, title: CLIPSeg Model Loader, class type: CLIPSeg Model Loader
[ComfyUI] !!! Exception during processing !!! Incorrect path_or_model_id: 'models--CIDAS--clipseg-rd64-refined'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
[ComfyUI] Traceback (most recent call last):
[ComfyUI] File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/transformers/utils/hub.py", line 403, in cached_file
[ComfyUI] resolved_file = hf_hub_download(
[ComfyUI] File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
[ComfyUI] validate_repo_id(arg_value)
[ComfyUI] File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 167, in validate_repo_id
[ComfyUI] raise HFValidationError(f"Cannot have -- or .. in repo_id: '{repo_id}'.")
[ComfyUI] huggingface_hub.errors.HFValidationError: Cannot have -- or .. in repo_id: 'models--CIDAS--clipseg-rd64-refined'.
[ComfyUI]
[ComfyUI] The above exception was the direct cause of the following exception:
[ComfyUI]
[ComfyUI] Traceback (most recent call last):
[ComfyUI] File "/src/ComfyUI/execution.py", line 323, in execute
[ComfyUI] output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
[ComfyUI] File "/src/ComfyUI/execution.py", line 198, in get_output_data
[ComfyUI] return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
[ComfyUI] File "/src/ComfyUI/execution.py", line 169, in _map_node_over_list
[ComfyUI] process_inputs(input_dict, i)
[ComfyUI] File "/src/ComfyUI/execution.py", line 158, in process_inputs
[ComfyUI] results.append(getattr(obj, func)(**inputs))
[ComfyUI] File "/src/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 11389, in clipseg_model
[ComfyUI] inputs = CLIPSegProcessor.from_pretrained(model, cache_dir=cache)
[ComfyUI] File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/transformers/processing_utils.py", line 944, in from_pretrained
[ComfyUI] args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
[ComfyUI] File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/transformers/processing_utils.py", line 990, in _get_arguments_from_pretrained
[ComfyUI] args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
[ComfyUI] File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/transformers/image_processing_base.py", line 206, in from_pretrained
[ComfyUI] image_processor_dict, kwargs = cls.get_image_processor_dict(pretrained_model_name_or_path, **kwargs)
[ComfyUI] File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/transformers/image_processing_base.py", line 335, in get_image_processor_dict
[ComfyUI] resolved_image_processor_file = cached_file(
[ComfyUI] File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/transformers/utils/hub.py", line 469, in cached_file
[ComfyUI] raise EnvironmentError(
[ComfyUI] OSError: Incorrect path_or_model_id: 'models--CIDAS--clipseg-rd64-refined'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
[ComfyUI]
[ComfyUI] Prompt executed in 0.21 seconds
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/cog/server/worker.py", line 352, in _predict
result = predict(**payload)
File "/src/predict.py", line 137, in predict
self.comfyUI.run_workflow(wf)
File "/src/comfyui.py", line 300, in run_workflow
self.wait_for_prompt_completion(workflow, prompt_id)
File "/src/comfyui.py", line 242, in wait_for_prompt_completion
raise Exception(
Exception: There was an error executing your workflow:
{
"type": "execution_error",
"data": {
"prompt_id": "4aaeb088-7ed2-4177-9bd0-9087dd7b195a",
"node_id": "165",
"node_type": "CLIPSeg Model Loader",
"executed": [],
"exception_message": "Incorrect path_or_model_id: 'models--CIDAS--clipseg-rd64-refined'. Please provide either the path to a local folder or the repo_id of a model on the Hub.",
"exception_type": "OSError",
"traceback": [
"  File \"/src/ComfyUI/execution.py\", line 323, in execute\n    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n",
"  File \"/src/ComfyUI/execution.py\", line 198, in get_output_data\n    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n",
"  File \"/src/ComfyUI/execution.py\", line 169, in _map_node_over_list\n    process_inputs(input_dict, i)\n",
"  File \"/src/ComfyUI/execution.py\", line 158, in process_inputs\n    results.append(getattr(obj, func)(**inputs))\n",
"  File \"/src/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py\", line 11389, in clipseg_model\n    inputs = CLIPSegProcessor.from_pretrained(model, cache_dir=cache)\n",
"  File \"/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/transformers/processing_utils.py\", line 944, in from_pretrained\n    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)\n",
"  File \"/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/transformers/processing_utils.py\", line 990, in _get_arguments_from_pretrained\n    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))\n",
"  File \"/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/transformers/image_processing_base.py\", line 206, in from_pretrained\n    image_processor_dict, kwargs = cls.get_image_processor_dict(pretrained_model_name_or_path, **kwargs)\n",
"  File \"/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/transformers/image_processing_base.py\", line 335, in get_image_processor_dict\n    resolved_image_processor_file = cached_file(\n",
"  File \"/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/transformers/utils/hub.py\", line 469, in cached_file\n    raise EnvironmentError(\n"
],
"current_inputs": {
"model": [
"models--CIDAS--clipseg-rd64-refined"
]
},
"current_outputs": [
"67",
"165",
"168",
"163",
"102",
"166",
"167",
"169",
"164"
],
"timestamp": 1732878980905
}
}`

**Comment by fofr** [comment]
Ah, I believe you need to change this:

```
"model": [
"models--CIDAS--clipseg-rd64-refined"
]
```

to

```
"model": [
"CIDAS/clipseg-rd64-refined"
]
```

The clipseg weights will still download.

**Comment by mehmetsat** [comment]
Greatt download issue is solved. There still is an issue about transformers' latest version but the fix is downgrading the transformers which is mentioned here fyi
[transformers issue](https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/820)
I can do it in my fork thankss @fofr
