### ISSUE TITLE
Request for LoRA Weights: Not Artists Styles for Pony Diffusion V6 XL

### ISSUE THREAD

**Issue by AGuski** [fofr/cog-comfyui#213]
Hi, I would love to see these great and widely usable weights for Pony Diffusion v6 on replicate, since you already have the base model available:
[https://civitai.com/models/264290/not-artists-styles-for-pony-diffusion-v6-xl](https://civitai.com/models/264290/not-artists-styles-for-pony-diffusion-v6-xl)

Personally I am specifically interested in the [Smooth Anime 2](https://civitai.com/models/264290?modelVersionId=333607), but I think they are all pretty good.

Thank you!

**Comment by fofr** [comment]
I've added both of these loras in d000782
