### ISSUE TITLE
Request for LoRA Weights: extra realism loras for FLUX

### ISSUE THREAD

**Issue by devoln** [fofr/cog-comfyui#215]
Hi! I can only see flux-RealismLora.safetensors which doesn't seem realistic enough to me. Can you add more please?

Specifically, I'm using this one in my project, so I need its support to migrate to Replicate:
https://huggingface.co/prithivMLmods/Canopus-LoRA-Flux-UltraRealism-2.0

The following is considered a newer version of the above and also may be useful:
https://huggingface.co/prithivMLmods/Ton618-Epic-Realism-Flux-LoRA

**Comment by fofr** [comment]
I've added both in 4e32deb

Note the second one is named [Ton618-Epic-Realism-Flux-LoRA.safetensors](https://huggingface.co/prithivMLmods/Ton618-Epic-Realism-Flux-LoRA)
