### ISSUE TITLE
clip_l.safetensors unavailable

### ISSUE THREAD

**Issue by Alecattie** [fofr/cog-comfyui#217]
Hello I am getting this error on predicition: 

clip_l.safetensors unavailable. View the list of available weights: https://github.com/fofr/cog-comfyui/blob/main/supported_weights.md

Even though i see its suppored on https://github.com/fofr/cog-comfyui/blob/main/supported_weights.md

I am using dual clip loader for flux 

  "279": {
    "inputs": {
      "clip_name1": "clip_l.safetensors",
      "clip_name2": "t5xxl_fp16.safetensors",
      "type": "flux"
    },
    "class_type": "DualCLIPLoader"
  },

Thank you for your help

**Comment by redstarxz** [comment]
> Hello I am getting this error on predicition:
> 
> clip_l.safetensors unavailable. View the list of available weights: https://github.com/fofr/cog-comfyui/blob/main/supported_weights.md
> 
> Even though i see its suppored on https://github.com/fofr/cog-comfyui/blob/main/supported_weights.md
> 
> I am using dual clip loader for flux
> 
> "279": { "inputs": { "clip_name1": "clip_l.safetensors", "clip_name2": "t5xxl_fp16.safetensors", "type": "flux" }, "class_type": "DualCLIPLoader" },
> 
> Thank you for your help

I built the image with the latest code and encountered the same issue after running it on r8. but  it works on local env.
