### ISSUE TITLE
How do we get flux models stream response for image generation

### ISSUE THREAD

**Issue by ABZig** [fofr/cog-comfyui#218]
krea.ai (https://www.krea.ai/apps/image/flux) as you can see and run the flux models, you will get a response in a stream, kind of an animation feel. Does ComfyUI Flux models support anything like that to generate images?

I have checked in the replicate flux family but didn't find anything that can help me out.

![Screenshot 2024-12-11 at 3 11 24 PM](https://github.com/user-attachments/assets/2353d2c3-6540-40c9-8cc9-bf52fb4c0989)

**Comment by fofr** [comment]
This isn't supported at the moment.
