### ISSUE TITLE
Flux regional prompting (Fluxtapoz)

### ISSUE THREAD

**Issue by MJvanAdrichem** [fofr/cog-comfyui#219]
https://github.com/logtd/ComfyUI-Fluxtapoz/tree/main?tab=readme-ov-file#regional-prompting 

For regional prompting you'd need the nodes "Create Flux Rergional Cond" and "Apply Flux Regional Conds", but these are not yet included in commit "4d30397" of the Fluxtapoz repo.

The current custom_node supported is:
"repo": "https://github.com/logtd/ComfyUI-Fluxtapoz",
"commit": "4d30397"

**Comment by lizaleonekal** [comment]
Seconding this, would be great!
