### ISSUE TITLE
Request for model weight: SDXL/dreamshaperXL_sfwV2TurboDPMSDE.safetensors

### ISSUE THREAD

**Issue by vikrambhiwapurkar-bst** [fofr/cog-comfyui#221]
Hi 
Can you please add this model

Link where you can find it:-    https://civitai.com/models/112902?modelVersionId=341981

**Comment by fofr** [comment]
Added in dd91f6b

**Comment by nitinkalra-bst** [comment]
@fofr can you please add these custom nodes also, mentioned in https://github.com/fofr/cog-comfyui/issues/220
