### ISSUE TITLE
weights_manifest.py code issue

### ISSUE THREAD

**Issue by redstarxz** [fofr/cog-comfyui#223]
Hi,  

I found the newest code in weights_manifest.py may cause bug when run some workflow.  please check again.

```
          if directory_name.lower() == "clip" and "clip-vit-large-patch14" in keys:
                return {
                    "clip-vit-large-patch14": {
                        "url": f"{BASE_URL}/clip/clip-vit-large-patch14.tar",
                        "dest": f"{MODELS_PATH}/clip",
                    }
                }
```
the code above ignore the remaining key in clip directory,  lead to some wegihts unavailable.

**Comment by fofr** [comment]
Thank you for raising, I have fixed here:
https://github.com/fofr/cog-comfyui/commit/98a68324cb330620c421ea61d5642675ae3dd9aa
