### ISSUE TITLE
[Error]:Missing device driver

### ISSUE THREAD

**Issue by ysj16** [fofr/cog-comfyui#234]
Host Environment: Ubuntu 24.04, 4070ti, Driver Version: 550.120, CUDA Version: 12.4

When I executing ````sudo cog run -p 8188 bash````, the following error occurs at the end:
````
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
Missing device driver, re-trying without GPU
````

I can enter the container, but when starting ComfyUI, it gives the following error:
````
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
````

**Comment by Unpackyourdream-Paprika** [comment]
same problem, how did you do that?
