### ISSUE TITLE
Useful Components to Add.

### ISSUE THREAD

**Issue by bestofajith** [fofr/cog-comfyui#24]
Hi, Thank you for the wonderful project!
It would be great if you could add the following open-source components.

**Nodes** _*Available in Comfy Manager_
Comfyroll Studio: https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes
Safety Checker: https://github.com/42lux/ComfyUI-safety-checker

**Model**
AbsoluteReality: https://civitai.com/models/81458/absolutereality

**Embedding Picker**
FastNegativeV2: https://civitai.com/models/71961/fast-negative-embedding-fastnegativev2

**Lora**
Detail Enhancer: https://civitai.com/models/82098/add-more-details-detail-enhancer-tweaker-lora

Thanks a lot!

**Comment by bestofajith** [comment]
Thank you so much, I really appreciate it. Also, do you have any plans to add the Safety Checker node? Or are there any safety filters included in the added nodes?

Best

**Comment by bestofajith** [comment]
Additionally, could you add 'Ultramix Balanced' for upscaling?
You already have the Smooth version, but it turned out to be overly smooth/blurry.

Link: https://civitai.com/models/147806/ultramix

thanks

**Comment by fofr** [comment]
I've added here:
https://github.com/fofr/cog-comfyui/commit/65224e3d0abed3490374c4eccd3c6a893c27c4ee

**Comment by bestofajith** [comment]
> Thank you so much, I really appreciate it. Also, do you have any plans to add the Safety Checker node? Or are there any safety filters included in the added nodes?
> 
> Best

Are there any safety nodes like this? https://github.com/42lux/ComfyUI-safety-checker

**Comment by fofr** [comment]
@bestofajith I think I'll add a safety checker as default to the model, rather than as a node. Like on this model:
https://replicate.com/fofr/txt2img

It uses the same safety checker ML model to determine if an image is safe or not. Would that suffice?

**Comment by bestofajith** [comment]
> @bestofajith I think I'll add a safety checker as default to the model, rather than as a node. Like on this model: https://replicate.com/fofr/txt2img
> 
> It uses the same safety checker ML model to determine if an image is safe or not. Would that suffice?

Thanks! This will work on SD1.5 also, right?
