### ISSUE TITLE
instant-id not working

### ISSUE THREAD

**Issue by ccakmak60** [fofr/cog-comfyui#32]
does instant-id not work, because I used the default instant-id workflow in the examples folder and it fails. other workflows with instant-id also keep failing.

**Comment by fofr** [comment]
I updated the instant-id custom node today, I think there might have been some breaking changes. I'll double check the examples and upload new ones.

To confirm this you could try running same on the previous version of the model.

**Comment by jamesblackwell** [comment]
it works on 4d4aa1a0db2b6511a482cf9b973b21a4d97b63458d05d7c7232ba9587cbe1ce8 but the latest seems to break
