### ISSUE TITLE
Making it suitable for my own workflow

### ISSUE THREAD

**Issue by flamed0g** [fofr/cog-comfyui#33]
Hi there,

I want to give this template a try to run my workflow on Replicate. However, there are quite a few custom nodes installed that my workflow does not use. I was wondering if there are any benefits of forking this repository and stripping out the checkpoints and nodes that I do need, in terms of computing time (Replicate costs).

If I do fork the repository, I would like to add a checkpoint myself but I can't figure out how you actually add those. I see the list of checkpoints in `weights.json` but I do not see any CivitAI e.g. download URLs so are these `safetensors` files hosted somewhere else to download?

**Ideal situation for me would be:**
- Fork the repository, remove the custom nodes, checkpoints and LoRa’s that my workflow doesn’t use. Not sure if this has any benefits in terms of performance.
- Add the checkpoint, LoRa and upscaler models myself through some downloadable URL (CivitAI or Huggingface).

It would also be great (for my use case) to ‘bake’ my checkpoint in the image to avoid any downloading time when the generation starts and avoid extra Replicate costs. But not quite sure how to do this either since I saw that most weights are being downloaded on runtime (when a prediction starts).

**Comment by drommerkiller** [comment]
I have these same questions. My workflow has many custom nodes that are not in this install and i use different models.
Instructions how to fork this so it can be pushed to replicate would be nice.

**Comment by fofr** [comment]
I've shipped a new feature that lets you upload:

- checkpoints
- loras
- embeddings
- controlnets
- animatediff motion models and loras

You need to use HuggingFace or CivitAI urls

https://replicate.com/fofr/any-comfyui-workflow/train

Check the training logs to see what filenames to use in your workflow JSON. For example:

```
Downloading from HuggingFace:
...
Size of the tar file: 217.88 MB
====================================
When using your new model, use these filenames in your JSON workflow:
araminta_k_midsommar_cartoon.safetensors
```

**Comment by bertagknowles** [comment]
May I know the answer to this question please:   there are quite a few custom nodes installed that my workflow does not use. I was wondering if there are any benefits of forking this repository and stripping out the checkpoints and nodes that I do need, in terms of computing time (Replicate costs). 
Are there any performance benefits if we remove the extra checkpoints and nodes and will this save replicate costs?
