### ISSUE TITLE
ComfyUI-Impact-Pack is missing dependencies

### ISSUE THREAD

**Issue by Six6pounder** [fofr/cog-comfyui#36]
### Description
When running the script `main.py` in, the program encounters an unexpected behavior. I tried to install using `pip install -r requirements.txt` inside ComfyUI-Impact-Pack folder and also `Python install.py` but still the same error.  I also ran `./scripts/clone_plugins.sh` after cloning the repo

### Steps to Reproduce
1. Run the script `main.py` with the command `python main.py --listen 0.0.0.0`.

### Expected Behavior
The script should run without any issues and provide the expected output.

### Actual Behavior
The script encounters an issue during execution.

### Environment
- Operating System: Linux (Ubuntu)
- Shell: zsh 5.9
- Python Version: 2.2.1+cu121
- GPU: NVIDIA GeForce RTX 3080

```
Running 'bash' in Docker with the current directory mounted as a volume...
root@c484976c6fd1:/src# cd ComfyUI/
root@c484976c6fd1:/src/ComfyUI# python main.py --listen 0.0.0.0
Total VRAM 9976 MB, total RAM 31820 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
[tinyterraNodes] Loaded
### Loading: ComfyUI-Inspire-Pack (V0.59)
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
Total VRAM 9976 MB, total RAM 31820 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
VAE dtype: torch.bfloat16
[ReActor] - STATUS - Running v0.4.1-b9 in ComfyUI
Torch version: 2.2.1+cu121
FizzleDorf Custom Nodes: Loaded
### Loading: ComfyUI-Impact-Pack (V4.76.1)
### ComfyUI-Impact-Pack is missing dependencies
```

**Comment by fofr** [comment]
Can you find out which dependency is missing?

Try temporarily changing line 67 in ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py

To:

```
except ImportError as e:
    missing_dependency = str(e).split("No module named ")[-1]
    print(f"### ComfyUI-Impact-Pack is missing dependency: {missing_dependency}")
    exit(1)
```

**Comment by fofr** [comment]
Also, if you aren't using ImpactPack, you could remove it.

**Comment by Lady-vamp** [comment]
> Can you find out which dependency is missing?
> 
> Try temporarily changing line 67 in `ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py`
> 
> To:
> 
> ```
> except ImportError as e:
>     missing_dependency = str(e).split("No module named ")[-1]
>     print(f"### ComfyUI-Impact-Pack is missing dependency: {missing_dependency}")
>     exit(1)
> ```

I edited the code as:
```
except Exception as e:
    # import importlib
    # print("### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)")
    # do_install()
    missing_dependency = str(e).split("No module named ")[-1]
    print(f"### ComfyUI-Impact-Pack is missing dependency: {missing_dependency}")
    exit(1)

```
and the output is: 
```
### Loading: ComfyUI-Impact-Pack (V4.76.1)
### ComfyUI-Impact-Pack is missing dependency: module 'cv2.gapi.wip.draw' has no attribute 'Text'
```

**Comment by fofr** [comment]
It looks like it could be this:
https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/251
https://github.com/Gourieff/comfyui-reactor-node#iv-controlnet-aux-node-import-failed-error-when-using-with-reactor-node

Try changing `cog.yaml` from:

```diff
-- opencv-python-headless>=4.0.1.24
+- opencv-python-headless>=4.9.0.80
```

**Comment by Lady-vamp** [comment]
> It looks like it could be this: [cubiq/ComfyUI_IPAdapter_plus#251](https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/251) https://github.com/Gourieff/comfyui-reactor-node#iv-controlnet-aux-node-import-failed-error-when-using-with-reactor-node
> 
> Try changing `cog.yaml` from:
> 
> ```diff
> -- opencv-python-headless>=4.0.1.24
> +- opencv-python-headless>=4.9.0.80
> ```

Still the same output, just to be sure that I have the right opencv version installed I ran:
```
root@e94e1ff32d71:/src/ComfyUI# pip show opencv-python-headless          
Name: opencv-python-headless
Version: 4.9.0.80
Summary: Wrapper package for OpenCV python bindings.
Home-page: https://github.com/opencv/opencv-python
Author: 
Author-email: 
License: Apache 2.0
Location: /root/.pyenv/versions/3.10.6/lib/python3.10/site-packages
Requires: numpy, numpy, numpy, numpy
Required-by: albumentations
```

**Comment by Lady-vamp** [comment]
`pip install opencv-python==4.6.0.66` seems to have fixed that issue, now it runs correctly. No idea why it works with that specific version

**Comment by Lady-vamp** [comment]
> `pip install opencv-python==4.6.0.66` seems to have fixed that issue, now it runs correctly. No idea why it works with that specific version

@fofr Sorry for all these messages, I should have tested before but I noticed it only works if inside the cog I remove and then reinstall with `pip install opencv-python==4.6.0.66` otherwise I get the error I posted above, in the `cog.yaml` I have set the 4.6.0.66 version but it won't work until inside the docker I reinstall it. 
Also If I restart the cog machine I get the same error again.
To make it work basically I have to:
`sudo cog run -p 8188 bash`
` pip uninstall opencv-python`
` pip install opencv-python==4.6.0.66`

**Comment by fofr** [comment]
Closing this issue in a tidy up, feel free to reopen if you're still having issues.
