### ISSUE TITLE
Request for addirional weights and custom node

### ISSUE THREAD

**Issue by influgenai** [fofr/cog-comfyui#41]
Hey!
I really appreciate the job you are doing with enabling the comfyui workflows on replicate. Thank you for making my life easier :)

I would like to kindly ask if you could add one extra node and models?

- Easy padding node: https://github.com/ealkanat/comfyui_easy_padding
- Model: ligtning version 4.0 of: https://civitai.com/models/139562/realvisxl-v40
- controlnet model: [control_v11p_sd15_openpose.pth](https://huggingface.co/lllyasviel/ControlNet-v1-1/blob/main/control_v11p_sd15_openpose.pth)

I'm intending to run this workflow:

{
  "4": {
    "inputs": {
      "ckpt_name": "v1/epicrealism_naturalSinRC1VAE.safetensors"
    },
    "class_type": "CheckpointLoaderSimple",
    "_meta": {
      "title": "Load Checkpoint"
    }
  },
  "5": {
    "inputs": {
      "width": 712,
      "height": 944,
      "batch_size": 1
    },
    "class_type": "EmptyLatentImage",
    "_meta": {
      "title": "Empty Latent Image"
    }
  },
  "6": {
    "inputs": {
      "text": "photo of very skinny russian Анастасия Абакумов \n yong adult female, russian,skinny,(khaki eyes, long ginger hair:1.2), smile, in the empty white room, plain tshirt, wearing clothes, hyperdetailed photography, skin details,grainy,stunning, absurdes, official art, masterpiece, best quality, unity 8k wallpaper, ((photorealistic:1.4)), ultra detailed,perfect skin, (high_quality_masterpiece:1.2), soft rim lightning, modeling, closed eyes, open lips, plating with hair",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
  "7": {
    "inputs": {
      "text": "hands, elements in background, kid, child, children, NFSW, naked, nude, boobs, nipple, pussy, ass, bad anatomy, bad eyes, bad hands, bad nose, bad lips, poor quality, extra body parts, missing body parts, missing fingers, missing hands and legs, missing facial features, twisted body parts, twisted torso, unreal skin texture, poorly rendered clothes, extra body parts, extra hands, extra fingers, extra legs, extra abdomen, distorted body parts, distorted face, distorted arms, distorted fingers, amputation, disjointed body parts, disproportionate body parts asymmetrical body parts, bad lighting, multiple subjects, subject out of frame, shadows",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
  "42": {
    "inputs": {
      "seed": [
        "99",
        2
      ],
      "steps": 30,
      "cfg": 7,
      "sampler_name": "euler_ancestral",
      "scheduler": "karras",
      "denoise": 1,
      "model": [
        "4",
        0
      ],
      "positive": [
        "104",
        0
      ],
      "negative": [
        "7",
        0
      ],
      "latent_image": [
        "5",
        0
      ]
    },
    "class_type": "KSampler",
    "_meta": {
      "title": "KSampler"
    }
  },
  "46": {
    "inputs": {
      "samples": [
        "42",
        0
      ],
      "vae": [
        "4",
        2
      ]
    },
    "class_type": "VAEDecode",
    "_meta": {
      "title": "VAE Decode"
    }
  },
  "47": {
    "inputs": {
      "filename_prefix": "FaceIDPlus_v2_04",
      "images": [
        "112",
        0
      ]
    },
    "class_type": "SaveImage",
    "_meta": {
      "title": "Save Image"
    }
  },
  "99": {
    "inputs": {
      "number_type": "integer",
      "number": 780950033637.5
    },
    "class_type": "Constant Number",
    "_meta": {
      "title": "Constant Number"
    }
  },
  "100": {
    "inputs": {
      "detect_hand": "enable",
      "detect_body": "enable",
      "detect_face": "enable",
      "resolution": 512,
      "image": [
        "107",
        0
      ]
    },
    "class_type": "OpenposePreprocessor",
    "_meta": {
      "title": "OpenPose Pose"
    }
  },
  "101": {
    "inputs": {
      "image": "Zrzut ekranu 2024-03-4 o 23.52.28.png",
      "upload": "image"
    },
    "class_type": "LoadImage",
    "_meta": {
      "title": "Load Image"
    }
  },
  "102": {
    "inputs": {
      "images": [
        "100",
        0
      ]
    },
    "class_type": "PreviewImage",
    "_meta": {
      "title": "Preview Image"
    }
  },
  "104": {
    "inputs": {
      "strength": 0.7000000000000001,
      "conditioning": [
        "6",
        0
      ],
      "control_net": [
        "105",
        0
      ],
      "image": [
        "100",
        0
      ]
    },
    "class_type": "ControlNetApply",
    "_meta": {
      "title": "Apply ControlNet"
    }
  },
  "105": {
    "inputs": {
      "control_net_name": "v1/control_v11p_sd15_openpose.pth"
    },
    "class_type": "ControlNetLoader",
    "_meta": {
      "title": "Load ControlNet Model"
    }
  },
  "107": {
    "inputs": {
      "left": 128,
      "top": 128,
      "right": 128,
      "bottom": 128,
      "color": "#ffffff",
      "transparent": false,
      "image": [
        "101",
        0
      ]
    },
    "class_type": "comfyui-easy-padding",
    "_meta": {
      "title": "ComfyUI Easy Padding"
    }
  },
  "108": {
    "inputs": {
      "wildcard": "",
      "Select to add LoRA": "Select the LoRA to add to the text",
      "Select to add Wildcard": "Select the Wildcard to add to the text",
      "model": [
        "4",
        0
      ],
      "clip": [
        "4",
        1
      ],
      "vae": [
        "4",
        2
      ],
      "positive": [
        "6",
        0
      ],
      "negative": [
        "6",
        0
      ],
      "bbox_detector": [
        "109",
        0
      ],
      "sam_model_opt": [
        "110",
        0
      ],
      "segm_detector_opt": [
        "111",
        1
      ]
    },
    "class_type": "ToDetailerPipe",
    "_meta": {
      "title": "ToDetailerPipe"
    }
  },
  "109": {
    "inputs": {
      "model_name": "bbox/face_yolov8m.pt"
    },
    "class_type": "UltralyticsDetectorProvider",
    "_meta": {
      "title": "UltralyticsDetectorProvider"
    }
  },
  "110": {
    "inputs": {
      "model_name": "sam_vit_b_01ec64.pth",
      "device_mode": "AUTO"
    },
    "class_type": "SAMLoader",
    "_meta": {
      "title": "SAMLoader (Impact)"
    }
  },
  "111": {
    "inputs": {
      "model_name": "segm/person_yolov8m-seg.pt"
    },
    "class_type": "UltralyticsDetectorProvider",
    "_meta": {
      "title": "UltralyticsDetectorProvider"
    }
  },
  "112": {
    "inputs": {
      "guide_size": 786,
      "guide_size_for": true,
      "max_size": 1024,
      "seed": 0,
      "steps": 30,
      "cfg": 8,
      "sampler_name": "euler_ancestral",
      "scheduler": "karras",
      "denoise": 0.5,
      "feather": 5,
      "noise_mask": true,
      "force_inpaint": false,
      "bbox_threshold": 0.5,
      "bbox_dilation": 10,
      "bbox_crop_factor": 3,
      "sam_detection_hint": "center-1",
      "sam_dilation": 0,
      "sam_threshold": 0.93,
      "sam_bbox_expansion": 0,
      "sam_mask_hint_threshold": 0.7,
      "sam_mask_hint_use_negative": "False",
      "drop_size": 10,
      "refiner_ratio": 0.2,
      "cycle": 1,
      "inpaint_model": false,
      "noise_mask_feather": 10,
      "image": [
        "46",
        0
      ],
      "detailer_pipe": [
        "108",
        0
      ]
    },
    "class_type": "FaceDetailerPipe",
    "_meta": {
      "title": "FaceDetailer (pipe)"
    }
  },
  "113": {
    "inputs": {
      "images": [
        "112",
        2
      ]
    },
    "class_type": "PreviewImage",
    "_meta": {
      "title": "Preview Image"
    }
  },
  "114": {
    "inputs": {
      "images": [
        "112",
        1
      ]
    },
    "class_type": "PreviewImage",
    "_meta": {
      "title": "Preview Image"
    }
  }
}

Thank you so much!
W

**Comment by influgenai** [comment]
@fofr Hey, do you have any update on this? 
Maybe I could add the needed weights by myself somehow?
Thanks a lot! :)
W

**Comment by fofr** [comment]
These weights are already available:

- control_v11p_sd15_openpose.pth
- RealVisXL_V4.0_Lightning.safetensors

EasyPadding isn't a popular custom node, meaning I'm unlikely to add it to this repo as many won't need it. But feel free to fork and push your own.
