### ISSUE TITLE
Weight Unavailable 

### ISSUE THREAD

**Issue by ZekiJohn** [fofr/cog-comfyui#43]
Hello

I'm getting this error when I'm using my own weight dreamshaperXL_v21TurboDPMSDE.safetensors

dreamshaperXL_v21TurboDPMSDE.safetensors unavailable. View the list of available weights: https://github.com/fofr/cog-comfyui/blob/main/supported_weights.md

<img width="543" alt="image" src="https://github.com/fofr/cog-comfyui/assets/45900838/ee7bc61b-ddbb-444d-8c56-305462937ef7">

**Comment by fofr** [comment]
Or I could add the weights for you, but in this case I believe lightning is superior.

**Comment by ZekiJohn** [comment]
thanks for replying @fofr 
what is the difference between the turbo and lightning?

**Comment by fofr** [comment]
Lightning gives better quality images and can be used commercially
https://www.reddit.com/r/StableDiffusion/comments/1awmz5o/dreamshaper_xl_lightning_just_released_targeting/

You need to use a CFG of 2, 4 steps and a dpmsde sampler

**Comment by ZekiJohn** [comment]
Thank you for the suggestion!
Is it possible to clone the repo _**(fofr/cog-comfyui)**_, make my desired modifications, and then `cog push` it to my own repository on Replicate? Will there be any problems if I proceed with this plan?

**Comment by fofr** [comment]
You can definitely do that, yes.
