### ISSUE TITLE
TEEDPreprocessor and deepfashion2 

### ISSUE THREAD

**Issue by ufreak3333** [fofr/cog-comfyui#44]
![Ekran görüntüsü 2024-03-10 153041](https://github.com/fofr/cog-comfyui/assets/110104716/234f7b4d-d690-4c75-83ae-986ad5708fd0)

Can you add these weights to replicate ?

**Comment by fofr** [comment]
Sure, do you have links for them?

**Comment by ufreak3333** [comment]
for TEEDPrepressesor: 
https://github.com/Fannovel16/comfyui_controlnet_aux 

for deepfashion2
https://huggingface.co/Bingsu/adetailer/tree/main

and there is nothing about pattern generation in Replicate if you add this custom node it would be very helpful when ı want to generate seamless patterns:

https://github.com/spinagon/ComfyUI-seamless-tiling

**Comment by fofr** [comment]
TEEDPreprocessor added in 443a4ea

**Comment by fofr** [comment]
Holding off on deepfashion regarding:
https://huggingface.co/Bingsu/adetailer/discussions/4

**Comment by fofr** [comment]
Closing this for now. If you're still interesting seamless tiling, I can add that as a separate model, let me know.
