### ISSUE TITLE
Custom LORA request

### ISSUE THREAD

**Issue by daveka95** [fofr/cog-comfyui#47]
Would it be possible to add support for a custom LoRA?

**Comment by fofr** [comment]
What lora do you need to add?

**Comment by daveka95** [comment]
Thank you for the reply. I want to create my LoRA on replicate and use URL with the result in my ComfyUI workflow. Would it be possible to add such feature?

**Comment by daveka95** [comment]
I would also appreciate it if you could add:

**LORA:**
https://civitai.com/models/339001?modelVersionId=379582

**Checkpoints:**
https://civitai.com/models/351347/mklan-sfw-and-nsfw-lightning-dpo-edition?modelVersionId=398126
https://civitai.com/models/194768?modelVersionId=395827
https://civitai.com/models/351172/truetolifesdxl-lightning 

**Custom Node:**
https://github.com/42lux/ComfyUI-safety-checker 

This would be very helpful. Thank you in advance!

**Comment by xpluscal** [comment]
hey @fofr I'd love to add the ip-adapter sd15 faceID lora to the lora folder - is this on weights.replicate yet or what would be the process to add it?

**Comment by fofr** [comment]
- I've added `jibMixRealisticXL_v10Lightning46Step.safetensors` today
- It looks like truetolifesdxl-lightning has been taken down
- I couldn't find a solely sfw mklan model to add
- I think I might spin out ComfyUI VLM as a separate model as it'll make the model a lot larger and potentially slower for other users

**Comment by fofr** [comment]
If you're still interested in using the lora and safety-checker, feel free to reopen this issue and I can add them.
