### ISSUE TITLE
Essential LORAs and EMBEDDINGs

### ISSUE THREAD

**Issue by bestofajith** [fofr/cog-comfyui#48]
Hi, It would be very helpful if you added the following data.

EMBEDDINGS:
1. verybadimagenegative_v1.3 - https://civitai.com/models/11772/verybadimagenegative?modelVersionId=25820
2. epiCNegative - https://civitai.com/models/89484?modelVersionId=95263
3. epiCRealism - https://civitai.com/models/89484?modelVersionId=95256

LORAs:
1. Detail Slider - https://civitai.com/models/153562/detail-slider-lora
2. Weight Slider v2.0 - https://civitai.com/models/112552/weight-slider-lora
3. People Count Slider - https://civitai.com/models/114104/people-count-slider-lora
4. Gender Slider - https://civitai.com/models/112988/gender-slider-lora

Thanks for your work
Radnus

**Comment by fofr** [comment]
Those LORA links are 404ing for me.

**Comment by fofr** [comment]
I've added:

- [verybadimagenegative_v1.3.pt](https://civitai.com/models/11772/verybadimagenegative)
- [epiCNegative.pt](https://civitai.com/models/89484?modelVersionId=95256)
- [epiCRealism.pt](https://civitai.com/models/89484?modelVersionId=95263)

**Comment by fofr** [comment]
Closing for now, but I'm happy for you to reopen this if you add new lora links.

**Comment by bestofajith** [comment]
Hi, Thank You!
Can you please add these also?

**Ultralytics**
[hair_yolov8n-seg_60.pt](https://github.com/hben35096/assets/releases/tag/yolo8)

**Lora**
Weight Slider - https://civitai.com/models/180008?modelVersionId=202032
Age Slider - https://civitai.com/models/179792/age-slider
SDXLrender - https://civitai.com/models/171159?modelVersionId=236130

**Embeddings**
Juggernaut Negative - https://civitai.com/models/81563/juggernaut-negative-embedding


It would be great to see these assets go live!
Cheers,
