### ISSUE TITLE
LCM model for AnimateDiff + More LCM weights

### ISSUE THREAD

**Issue by drommerkiller** [fofr/cog-comfyui#51]
AnimateDiff models are updated with lightning models, but the AnimateDiff LCM model is missing.
https://civitai.com/models/326698/animatediff-lcm-motion-model

Suggestion for 1.5 LCM models that work well with AnimateDiff:
https://civitai.com/models/232228?modelVersionId=262126
https://civitai.com/models/306814/photon-lcm
https://civitai.com/models/337966/delusions-lcm

Most of my AnimateDiff workflows use only LCM workflow as its fast and better quality than lighting.

**Comment by fofr** [comment]
I've added the following:

- [animatediffLCMMotion_v10.ckpt](https://civitai.com/models/326698/animatediff-lcm-motion-model)
- [realisticLCMBYStable_v10.safetensors](https://civitai.com/models/232228?modelVersionId=262126)
- [photonLCM_v10.safetensors](https://civitai.com/models/306814/photon-lcm)

I didn't add delusions as it was non-commercial.
