### ISSUE TITLE
IpAdapter NOT working

### ISSUE THREAD

**Issue by triton2030** [fofr/cog-comfyui#52]
Hello
IpAdapter had new breaking updated recently, sad but the upgrade is great.

I'm using public version because i don't know how to code.
And this is the fastest way to test things on 48 gb GPU for me.
So it would be cool to update all the custom nodes at least once once a week

**Comment by fofr** [comment]
This is now updated in https://github.com/fofr/cog-comfyui/pull/54 and available on https://replicate.com/fofr/any-comfyui-workflow
