### ISSUE TITLE
Request for Marigold Depth Estimation Nodes

### ISSUE THREAD

**Issue by Sagnik2810Sarkar** [fofr/cog-comfyui#53]
I would like to use Marigold Depth Estimation on my SDXL depth controlnet workflow so here's the link to the nodes that would be required: https://github.com/kijai/ComfyUI-Marigold

Highly appreciate any efforts you put in!

**Comment by fofr** [comment]
Closing this one for now. Decided not to add it as the Marigold depth estimations are very slow. But happy to reassess if more people need this.
