### ISSUE TITLE
Support custom LoRA request

### ISSUE THREAD

**Issue by Goktug** [fofr/cog-comfyui#58]
Hi

Could you please support the following custom LoRAs?

- https://civitai.com/models/310235/glowneon-xl-lora?modelVersionId=348189
- https://civitai.com/models/122359/detail-tweaker-xl?modelVersionId=135867
- https://civitai.com/models/295100/aesthetic-anime-lora?modelVersionId=331598

Thanks

**Comment by fofr** [comment]
I've added:

- [glowneon_xl_v1.safetensors](https://civitai.com/models/310235/glowneon-xl-lora)
- [add-detail-xl.safetensors](https://civitai.com/models/122359/detail-tweaker-xl)
- [aesthetic_anime_v1s.safetensors](https://civitai.com/models/295100/aesthetic-anime-lora)
