### ISSUE TITLE
Request for clipseg model and segment-anything model

### ISSUE THREAD

**Issue by LLSean** [fofr/cog-comfyui#6]
Thanks for your great work. Can you add clipseg and segment-anything model in comfyui?

**Comment by fofr** [comment]
Do you have links to the models?

**Comment by LLSean** [comment]
Yeah. 
clipseg:
https://huggingface.co/CIDAS/clipseg-rd64-refined

segment-anything:
default or vit_h: [ViT-H SAM model.](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth)
vit_l: [ViT-L SAM model.](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth)
vit_b: [ViT-B SAM model.](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth)

**Comment by fofr** [comment]
And how are you using these in Comfy?

**Comment by LLSean** [comment]
I used these repos: 
https://github.com/shadowcz007/comfyui-mixlab-nodes/blob/main/nodes/Clipseg.py
https://github.com/storyicon/comfyui_segment_anything/blob/main/node.py

Thanks for your replying!

**Comment by fofr** [comment]
I'm adding the 3x SAM weights in this PR:
https://github.com/fofr/cog-comfyui/pull/22

They were needed for the ComfyUI-Impact-Pack

**Comment by LLSean** [comment]
Thanks for your work!

**Comment by fofr** [comment]
comfyui_segment_anything:
https://github.com/fofr/cog-comfyui/pull/26
