### ISSUE TITLE
Request for Rundiffusion XL weights and an Impact node error

### ISSUE THREAD

**Issue by ashleymarkfletcher** [fofr/cog-comfyui#60]
Please could you add the weights for [https://civitai.com/models/120964/rundiffusion-xl](https://civitai.com/models/120964/rundiffusion-xl) ?

Also, I'm having an issue with a KeyError when using 'DetailerForEach' in my workflow. It looks like it is part of the impact pack so not sure what's going on there. Any ideas?

**Comment by ashleymarkfletcher** [comment]
Looking into this further, it seems like recent updates to Impact have made some breaking changes, so the forked version you're using needs updating to re-align.

**Comment by ashleymarkfletcher** [comment]
Tried forking your Impact repo and merging the latest commits from the original Impact and it seemed to fix the issue. 

Now there's an issue with Photomaker having "Missing key(s) in state_dict" and "Unexpected key(s) in state_dict".

**Comment by fofr** [comment]
I'm adding rundiffusionXL_beta.safetensors to the supported checkpoints

**Comment by fofr** [comment]
I've updated ImpactPack to the latest version:
https://github.com/fofr/cog-comfyui/commit/291de14241310662583e7784398e73ba0ebbf8f9

**Comment by fofr** [comment]
I've also fixed the PhotoMaker implementation in #65

**Comment by ashleymarkfletcher** [comment]
Amazing, thanks!
