### ISSUE TITLE
Add Remove BG Custom Node, and PiXL 

### ISSUE THREAD

**Issue by akhil20187** [fofr/cog-comfyui#61]
Hi, 
I am using ComfyUI in replicate and is a great tool. I have a request

RemoveBG  Custom Node :  https://github.com/Jcd1230/rembg-comfyui-node
Checkpoint : PiXL Anime : https://civitai.com/models/260599/pixl-animecartooncomic-style

**Comment by fofr** [comment]
I've added pixlAnimeCartoonComic_v10.safetensors

**Comment by akhil20187** [comment]
Thanks a lot. Anything with Remove BG ?

**Comment by akhil20187** [comment]
@fofr  - Facing issue when I have added the pixlAnimeCartoonComic .  I believe it's getting added to Loras and not the checkpoint folder . Also if there are any other issue - Please check. 

Please find the log below:

====================================
[prediction-xtd3tea15nrgg0cexpavjpbrkm-logs.txt](https://github.com/fofr/cog-comfyui/files/15016248/prediction-xtd3tea15nrgg0cexpavjpbrkm-logs.txt)
Inputs uploaded to /tmp/inputs:
input.jpg
====================================
Checking inputs
✅ /tmp/inputs/input.jpg
====================================
Checking weights
⚠️  RMBG-1.4/model.pth is for non-commercial use only. Unless you have obtained a commercial license.
Details: https://github.com/fofr/cog-comfyui/blob/main/weights_licenses.md
⏳ Downloading RMBG-1.4/model.pth to ComfyUI/custom_nodes/ComfyUI-BRIA_AI-RMBG/RMBG-1.4
⌛️ Downloaded RMBG-1.4/model.pth in 0.27s, size: 168.53MB
✅ RMBG-1.4/model.pth
⏳ Downloading pixlAnimeCartoonComic_v10.safetensors to ComfyUI/models/loras
Error: unexpected http status http://storagecache-ch-las1-0.storagecache-ch-las1.tenant-replicate-prdsvcs.svc.cluster.local/weights.replicate.delivery/default/comfy-ui/loras/pixlAnimeCartoonComic_v10.safetensors.tar: 404 Not Found
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "/src/predict.py", line 89, in predict
wf = self.comfyUI.load_workflow(workflow_json or EXAMPLE_WORKFLOW_JSON)
File "/src/helpers/comfyui.py", line 232, in load_workflow
self.handle_weights(wf)
File "/src/helpers/comfyui.py", line 114, in handle_weights
self.weights_downloader.download_weights(weight)
File "/src/weights_downloader.py", line 24, in download_weights
self.download_if_not_exists(
File "/src/weights_downloader.py", line 43, in download_if_not_exists
self.download(weight_str, url, dest)
File "/src/weights_downloader.py", line 53, in download
subprocess.check_call(
File "/root/.pyenv/versions/3.10.6/lib/python3.10/subprocess.py", line 369, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pget', '--log-level', 'warn', '-xf', 'https://weights.replicate.delivery/default/comfy-ui/loras/pixlAnimeCartoonComic_v10.safetensors.tar', 'ComfyUI/models/loras']' returned non-zero exit status 1.

**Comment by akhil20187** [comment]
hey @fofr , looking forward to hear from you .

**Comment by fofr** [comment]
Sorry about that, the lora is indeed going to the wrong place, I will fix shortly.

**Comment by fofr** [comment]
Latent diffusion #66 is a good alternative to REMBG too

**Comment by akhil20187** [comment]
Great!! Thanks a lot for the update.
Will be checking it out.

Regards
Akhilesh

**Comment by fofr** [comment]
Closing for now, but please reopen if you need something.

**Comment by akhil20187** [comment]
Great! It’s working as well
