### ISSUE TITLE
Node Request (Semi Complex) (ComfyUI-Frame-Interpolation)

### ISSUE THREAD

**Issue by DrakenZA** [fofr/cog-comfyui#62]
It would be great if we could get https://github.com/Fannovel16/ComfyUI-Frame-Interpolation included. Mostly because it has some wacky stuff going on for install, and lots of models.

But i think it would be super useful as its used in many workflows just before VHS video combine to get a nice frame rate, and it supports pretty much every frame interp.

**Comment by fofr** [comment]
I'm adding this with support for:

- FILM
- RIFE
- AMT
- CAIN

The others need a `cupy` dependency I don't want to add as it'll increase the container size a lot
