### ISSUE TITLE
How do you convert a json file that looks like this into one that's compatible with cog-comfyui?

### ISSUE THREAD

**Issue by runshouse** [fofr/cog-comfyui#63]
{
  "last_node_id": 673,
  "last_link_id": 561,
  "nodes": [
    {
      "id": 53,
      "type": "ImageScale",
      "pos": [
        -19.653621835049712,
        -1707.8675132457402
      ],

**Comment by drommerkiller** [comment]
You need to save it in api format so it works. readme has instructions.

**Comment by fofr** [comment]
Check out the video here:
https://github.com/fofr/cog-comfyui?tab=readme-ov-file#1-get-your-api-json
