### ISSUE TITLE
Custom nodes request: KJNodes for rgb masks

### ISSUE THREAD

**Issue by drommerkiller** [fofr/cog-comfyui#64]
It would be great to have KJNodes included as it has the mask tools like rgb to mask that is used with AnimateDiff videos.
https://github.com/kijai/ComfyUI-KJNodes

Nice to have additions would be:
Rgthree-comfy mutie and bypass node utilities
https://github.com/rgthree/rgthree-comfy/tree/main

cg-use-everywhere seed everywhere node is damn useful when there is upscalers in the workflow. Unless there already is a node that does the same.
https://github.com/chrisgoringe/cg-use-everywhere

**Comment by fofr** [comment]
I'm looking into adding https://github.com/kijai/ComfyUI-KJNodes

**Comment by drommerkiller** [comment]
Great to hear!

IPAdapter was updated again with some new nodes and one is RGB mask node. I have not tested it yet, but it could work as KJNodes RGB mask works. KJNoses one is not limited to just red green and blue so i have used it with 6 color masks.
