### ISSUE TITLE
Why does replicate.com need to download the model every time I run it?

### ISSUE THREAD

**Issue by AzeWZ** [fofr/cog-comfyui#70]
the same json ,run two times.

**Comment by fofr** [comment]
You might not always be hitting the same GPU, or if it's restarted.
If you hit the same GPU and the model is still warm the weights will be available.

If you have a workflow you frequently use you might want to push a separate model that downloads those weights during setup instead.

**Comment by fofr** [comment]
For reference, these repos are examples of how I spun out workflows as specific models:

https://github.com/fofr/cog-face-to-many
https://github.com/fofr/cog-stickers
https://github.com/fofr/cog-video-morpher
