### ISSUE TITLE
workflow.json gone from the replicate page.

### ISSUE THREAD

**Issue by drommerkiller** [fofr/cog-comfyui#71]
Since you updated the https://replicate.com/fofr/any-comfyui-workflow
We cant run workflows anymore as it replaced with video generator that does not seem to work. 

Are you bringing back the "run any workflow" or it now replaced with that?
Also, this model worked earlier: animatediffLCMMotion_v10.ckpt but now it gives "model not found" error.

**Comment by fofr** [comment]
Fixed, sorry about this.

**Comment by drommerkiller** [comment]
@fofr Is it still undrer construction? The replicate looks now like it should be but api gives this error:
  "error": "Internal Server Error. Request to https://api.replicate.com/v1/predictions failed with status 422 Unprocessable Entity: {\"title\":\"Version disabled\",\"detail\":\"Sorry, this version is currently disabled.\",\"status\":422}\n."
  
  Is the api version now disabled?
  I used this: fofr/any-comfyui-workflow:d571d571599d4a157a922bd26405e1542b5077048951277c1352a2cba289661e
