### ISSUE TITLE
LORAs & more..

### ISSUE THREAD

**Issue by bestofajith** [fofr/cog-comfyui#72]
Hi, Can you please add these also?

**Ultralytics**
[hair_yolov8n-seg_60.pt](https://github.com/hben35096/assets/releases/tag/yolo8)

**Lora**
Weight Slider - https://civitai.com/models/180008?modelVersionId=202032
Age Slider - https://civitai.com/models/179792/age-slider
SDXLrender - https://civitai.com/models/171159?modelVersionId=236130

**Embeddings**
Juggernaut Negative - https://civitai.com/models/81563/juggernaut-negative-embedding

It would be great to see these assets go live!
Cheers,

_Originally posted by @bestofajith in https://github.com/fofr/cog-comfyui/issues/48#issuecomment-2073546968_

**Comment by fofr** [comment]
Added in https://github.com/fofr/cog-comfyui/commit/11b8be0bce17dad452f28295ffe4616446687c68

**Comment by bestofajith** [comment]
Thanks 👍
