### ISSUE TITLE
Request: SDXL Model (sdxlUnstableDiffusers_v11Rundiffusion)

### ISSUE THREAD

**Issue by DrakenZA** [fofr/cog-comfyui#77]
https://civitai.com/models/84040?modelVersionId=309729

https://civitai.com/api/download/models/309729?type=Model&format=SafeTensor&size=full&fp=fp16

It is a very nice 'general' SDXL fine tune. Ive struggled to find SDXL fine tunes that work well as a general 'base' model much like SDXL 1.0 but better.

If you have time to add it to the Replicate Repo/Your Cog, that would be great !

Thank you for your work.

**Comment by fofr** [comment]
I've added sdxlUnstableDiffusers_nihilmania and sdxlUnstableDiffusers_v11Rundiffusion 👍
