### ISSUE TITLE
error occured when run comfyui using the same prompts

### ISSUE THREAD

**Issue by WooXinyi** [fofr/cog-comfyui#79]
Thanks to your excellent work!
Since comfyui try to find last generated image if using identical txt2img workflow(same seeds), there will be error occured because the images in output directory have been removed before prediction.

**Comment by fofr** [comment]
I think this is happening because there is no easy way to tell ComfyUI to flush it's cache.

A quick way around it would be to run a quick and simple reset workflow beforehand, like this one:
https://github.com/fofr/cog-comfyui/blob/main/examples/api_workflows/reset.json

**Comment by fofr** [comment]
I'm adding an option to run the reset as part of the prediction to prevent this.

**Comment by fofr** [comment]
<img width="600" alt="Screenshot 2024-05-24 at 22 46 51" src="https://github.com/fofr/cog-comfyui/assets/319055/38ebbab2-0d42-4881-8f10-2a7ab6cd799f">

You can now use this feature if it happens again.

**Comment by Six6pounder** [comment]
> <img alt="Screenshot 2024-05-24 at 22 46 51" width="600" src="https://private-user-images.githubusercontent.com/319055/333742818-38ebbab2-0d42-4881-8f10-2a7ab6cd799f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDUxMDUsIm5iZiI6MTcxODcwNDgwNSwicGF0aCI6Ii8zMTkwNTUvMzMzNzQyODE4LTM4ZWJiYWIyLTBkNDItNDg4MS04ZjEwLTJhN2FiNmNkNzk5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMDAwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjM1YWFhYTM3ZTlkNmMzYWI2MTBlOGUzM2RlM2RlMTg2MzEzMWJlMTllMzU2NjYwOGFmOGVmNTdlZWQ0N2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NLkKTe_TpGENmykVjLgkwxRg8BLmk5wBrSQZ651HFDo">
> You can now use this feature if it happens again.

@fofr I have this issue as well, how can I use force_reset_cache in the code? iirc it was in the predict.py but I updated to new commit and I don't see it anymore. Also is it safe if I have multiple items in the queue to use that option?

**Comment by fofr** [comment]
Yep, that should be fine
