### ISSUE TITLE
Request Custom Node: Rgthree-comfy

### ISSUE THREAD

**Issue by crimpproduction** [fofr/cog-comfyui#80]
Hi, can you please add this custom node so I can use it in the workflow?
https://github.com/rgthree/rgthree-comfy

This would provide some usefull features for a more advance workflow.
I really appreciate your work. Thank you!

**Comment by fofr** [comment]
rgthree mostly looks like quality of life improvements while using ComfyUI itself.
Are there particular nodes that are useful when using through an API?

**Comment by crimpproduction** [comment]
Hi, thanks for the quick response!
It is indeed a quality of life feature that we use to build advance and
modular workflow. Which then we can easily access through the API for
deployment.
The most useful are probably the context nodes and the bypasser. That would
make frontend access and implementation more straight forward. It would
also help us artist to communicate with the frontend dev much easier. For
example to create feature to bypass or activate controlnet modules, to
reroute and change the pipeline with boolean input.
I'm pretty sure more people will find it useful to have this custom node
available in this replicate comfyui workflow.
Thank you

**Comment by fofr** [comment]
rgthree added in https://github.com/fofr/cog-comfyui/commit/41d80745c9dde9b1cc61d25af6d9398428569c3a
