### ISSUE TITLE
Issue when running InstantID face analysis

### ISSUE THREAD

**Issue by pocketens** [fofr/cog-comfyui#84]
Hello, I tried to add some InstantID to my comfyui flow, and everytime the API call runs now, the InstantID face analysis action produces a bevy of these messages/errors:

**2024-05-26 06:11:40.871530646 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 489, index: 3, mask: {2, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
It repeats this maybe 50 times, split between:**

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /src/ComfyUI/models/insightface/models/antelopev2/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0

for each onnx file that would ordinarily be in the antelopev2 folder. I will note, the workflow works fine on my PC, not via API.

I am hosting it on a PythonAnywhere webapp if that helps. 
And then runs through the rest of the workflow, but does not produce an image. I am not super experienced, so sorry about the question if its so basic, but is there away to "Specify the number of threads", or does the InstantIDFaceAnalysis not work as intended in the latest version. I have tried CPU, CUDA, and ROCM. 

I am hosting it on a PythonAnywhere webapp if that helps.

**Comment by fofr** [comment]
I've noticed this too, and attempted to debug without much success. But at the same time, the results always seemed to work for me so I didn't pursue.

**Comment by pocketens** [comment]
> I've noticed this too, and attempted to debug without much success. But at the same time, the results always seemed to work for me so I didn't pursue.

Thats the issue, I dont get any results. It says there is a URL, but there is "no input" on the prediction.

**Comment by fofr** [comment]
Do you have some example predictions I could take a look at to debug?
