### ISSUE TITLE
Request for adding `controlnet-zoe-depth-sdxl-1.0`

### ISSUE THREAD

**Issue by Goktug** [fofr/cog-comfyui#88]
Hi,

Could you please support [controlnet-zoe-depth-sdxl-1.0](https://huggingface.co/diffusers/controlnet-zoe-depth-sdxl-1.0)? 
I checked the supported weight but couldn't find this version of the Zoe Depth file.

Thanks a lot

**Comment by fofr** [comment]
Is that different to `depth-zoe-xl-v1.0-controlnet.safetensors`?

**Comment by Goktug** [comment]
@fofr Actually, I shared the wrong link in the first message. This is [the correct one.](https://huggingface.co/diffusers/controlnet-zoe-depth-sdxl-1.0) How can we make sure those are the same one?

**Comment by fofr** [comment]
They have different SHAs, I've now added https://huggingface.co/diffusers/controlnet-zoe-depth-sdxl-1.0 as `controlnet-zoe-depth-sdxl-1.0.safetensors`
