### ISSUE TITLE
Request for Attention Couple Support (cgem156-ComfyUI)

### ISSUE THREAD

**Issue by yelnady** [fofr/cog-comfyui#89]
Hello,

Creating images with different prompts for each region is challenging, I tried many different options to composite multiple prompts, but only this pack contains an implementation of attention couple that gives really awesome results. It's also way faster than using a latent couple. 

https://github.com/laksjdjf/cgem156-ComfyUI 

Could you please add it to the supported custom nodes?

Thanks

**Comment by fofr** [comment]
Added in https://github.com/fofr/cog-comfyui/commit/2bdc76dc1cb001bc1669d0d0c40467faac10063e
