### ISSUE TITLE
Request for weights

### ISSUE THREAD

**Issue by AR1011** [fofr/cog-comfyui#9]
Hello @fofr ,

Firstly thank you for your work getting this on replicate, would it be possible to request the following weights:

### Checkpoints:
- https://civitai.com/models/25694/epicrealism (Natural Sin RC1 VAE)

### Lora:
- https://civitai.com/models/110334?modelVersionId=118945
- https://civitai.com/models/58390/detail-tweaker-lora-lora

Thank you

**Comment by fofr** [comment]
@AR1011 I've added support for epicrealism_naturalSinRC1VAE.safetensors, I still need to add the loras.
