### ISSUE TITLE
Load lora from the replicate storage

### ISSUE THREAD

**Issue by sheikhfahad67** [fofr/cog-comfyui#90]
Hi there,

I have a question, I want to load the lora from the trained model.

I have deployed the stabilityAi/sdxl model in my workspace and use it to fine tune the model and in return it generates the LoRA and provide the API URL to use the fine-tuned model.

So, is there a way that I can just pass the link in the LoraLoadModel class in the workflow to use the LoRA automatically from the Replicate?

**Comment by Lalimec** [comment]
I remember seeing a Load Model From URL node somewhere. Maybe that will do it. I did a similar thing with load image from url nodes, where i just pass the url of the images to the wf instead of renaming zipping and uploading.

**Comment by Qualzz** [comment]
> I remember seeing a Load Model From URL node somewhere. Maybe that will do it. I did a similar thing with load image from url nodes, where i just pass the url of the images to the wf instead of renaming zipping and uploading.

This one ? [](https://github.com/pkpkTech/ComfyUI-TemporaryLoader)

**Comment by Lalimec** [comment]
Im not sure, but let me know if it works.

**Comment by sheikhfahad67** [comment]
Thanks @Qualzz and @Lalimec I have tried it hopefully it will works. But currently facing issue that is Replicate provides the URL of .tar file. So, ComfyUI through error while loading it.
