### ISSUE TITLE
Comfy Allor?

### ISSUE THREAD

**Issue by brainfuel** [fofr/cog-comfyui#95]
Can we get support for Allor please?

https://github.com/Nourepide/ComfyUI-Allor

Super handy set of nodes, especially when dealing with Alpha channel. 

We use it when upscaling images and retaining alpha.

  {
    "repo": "https://github.com/Nourepide/ComfyUI-Allor",
    "commit": "af9caec"
  }

**Comment by fofr** [comment]
It looks like this node might not be being actively updated any more
