### ISSUE TITLE
Request custome node: BrushNet

### ISSUE THREAD

**Issue by nlminh** [fofr/cog-comfyui#96]
Could you please add this custom node:
https://github.com/nullquant/ComfyUI-BrushNet

The code is based on
[BrushNet](https://github.com/TencentARC/BrushNet)
[PowerPaint](https://github.com/zhuang2002/PowerPaint)
[HiDiffusion](https://github.com/megvii-research/HiDiffusion)
[diffusers](https://github.com/huggingface/diffusers)

Thank you!

**Comment by fofr** [comment]
BrushNet works great, I plan to add this soon.

**Comment by nlminh** [comment]
Have you made a plan to add this node yet? @fofr

**Comment by fofr** [comment]
Taking a look at this now

**Comment by fofr** [comment]
I've added this:

https://github.com/fofr/cog-comfyui/commit/10fd26635930493cf91d4b6ca9eeb055a2cdac28

Examples:

https://github.com/fofr/cog-comfyui/commit/493c01c4665e879b1c1b9b2655627668114e2008

And it's now live on Replicate too.

Closing this, but please reopen if you have any issues.
