### ISSUE TITLE
Feature request: IC Light Support

### ISSUE THREAD

**Issue by martintmv-git** [fofr/cog-comfyui#99]
### Hey @fofr, 
It would be great to include support for IC Light models. I'm trying to deploy this workflow. ↓

![workflow](https://github.com/fofr/cog-comfyui/assets/101264514/8558c143-cdba-452b-9ecf-66e95c712bf7)

**Comment by zaheenrahman** [comment]
Which resizing node are you using? I'm trying to find one that is supported here.

**Comment by fofr** [comment]
This repo uses the native IC light implementation:
https://github.com/huchenlei/ComfyUI-IC-Light-Native

Can you try using that?

**Comment by fofr** [comment]
Closing for now as IC Light is supported by a different custom node.

**Comment by martintmv-git** [comment]
@zaheenrahman ImageResize+

@fofr thank you, I'll try native IC light!
